In [1]:
# Import Dependencies
import yfinance
import pandas_datareader as pdr
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import statsmodels.api as sm
import numpy as np

In [2]:
pdr.famafrench.get_available_datasets()

['F-F_Research_Data_Factors',
 'F-F_Research_Data_Factors_weekly',
 'F-F_Research_Data_Factors_daily',
 'F-F_Research_Data_5_Factors_2x3',
 'F-F_Research_Data_5_Factors_2x3_daily',
 'Portfolios_Formed_on_ME',
 'Portfolios_Formed_on_ME_Wout_Div',
 'Portfolios_Formed_on_ME_Daily',
 'Portfolios_Formed_on_BE-ME',
 'Portfolios_Formed_on_BE-ME_Wout_Div',
 'Portfolios_Formed_on_BE-ME_Daily',
 'Portfolios_Formed_on_OP',
 'Portfolios_Formed_on_OP_Wout_Div',
 'Portfolios_Formed_on_OP_Daily',
 'Portfolios_Formed_on_INV',
 'Portfolios_Formed_on_INV_Wout_Div',
 'Portfolios_Formed_on_INV_Daily',
 '6_Portfolios_2x3',
 '6_Portfolios_2x3_Wout_Div',
 '6_Portfolios_2x3_weekly',
 '6_Portfolios_2x3_daily',
 '25_Portfolios_5x5',
 '25_Portfolios_5x5_Wout_Div',
 '25_Portfolios_5x5_Daily',
 '100_Portfolios_10x10',
 '100_Portfolios_10x10_Wout_Div',
 '100_Portfolios_10x10_Daily',
 '6_Portfolios_ME_OP_2x3',
 '6_Portfolios_ME_OP_2x3_Wout_Div',
 '6_Portfolios_ME_OP_2x3_daily',
 '25_Portfolios_ME_OP_5x5',
 '25_Portfolios_ME_OP_5x5_Wout_Div',
 '25_Portfolios_ME_OP_5x5_daily',
 '100_Portfolios_ME_OP_10x10',
 '100_Portfolios_10x10_ME_OP_Wout_Div',
 '100_Portfolios_ME_OP_10x10_daily',
 '6_Portfolios_ME_INV_2x3',
 '6_Portfolios_ME_INV_2x3_Wout_Div',
 '6_Portfolios_ME_INV_2x3_daily',
 '25_Portfolios_ME_INV_5x5',
 '25_Portfolios_ME_INV_5x5_Wout_Div',
 '25_Portfolios_ME_INV_5x5_daily',
 '100_Portfolios_ME_INV_10x10',
 '100_Portfolios_10x10_ME_INV_Wout_Div',
 '100_Portfolios_ME_INV_10x10_daily',
 '25_Portfolios_BEME_OP_5x5',
 '25_Portfolios_BEME_OP_5x5_Wout_Div',
 '25_Portfolios_BEME_OP_5x5_daily',
 '25_Portfolios_BEME_INV_5x5',
 '25_Portfolios_BEME_INV_5x5_Wout_Div',
 '25_Portfolios_BEME_INV_5x5_daily',
 '25_Portfolios_OP_INV_5x5',
 '25_Portfolios_OP_INV_5x5_Wout_Div',
 '25_Portfolios_OP_INV_5x5_daily',
 '32_Portfolios_ME_BEME_OP_2x4x4',
 '32_Portfolios_ME_BEME_OP_2x4x4_Wout_Div',
 '32_Portfolios_ME_BEME_INV_2x4x4',
 '32_Portfolios_ME_BEME_INV_2x4x4_Wout_Div',
 '32_Portfolios_ME_OP_INV_2x4x4',
 '32_Portfolios_ME_OP_INV_2x4x4_Wout_Div',
 'Portfolios_Formed_on_E-P',
 'Portfolios_Formed_on_E-P_Wout_Div',
 'Portfolios_Formed_on_CF-P',
 'Portfolios_Formed_on_CF-P_Wout_Div',
 'Portfolios_Formed_on_D-P',
 'Portfolios_Formed_on_D-P_Wout_Div',
 '6_Portfolios_ME_EP_2x3',
 '6_Portfolios_ME_EP_2x3_Wout_Div',
 '6_Portfolios_ME_CFP_2x3',
 '6_Portfolios_ME_CFP_2x3_Wout_Div',
 '6_Portfolios_ME_DP_2x3',
 '6_Portfolios_ME_DP_2x3_Wout_Div',
 'F-F_Momentum_Factor',
 'F-F_Momentum_Factor_daily',
 '6_Portfolios_ME_Prior_12_2',
 '6_Portfolios_ME_Prior_12_2_Daily',
 '25_Portfolios_ME_Prior_12_2',
 '25_Portfolios_ME_Prior_12_2_Daily',
 '10_Portfolios_Prior_12_2',
 '10_Portfolios_Prior_12_2_Daily',
 'F-F_ST_Reversal_Factor',
 'F-F_ST_Reversal_Factor_daily',
 '6_Portfolios_ME_Prior_1_0',
 '6_Portfolios_ME_Prior_1_0_Daily',
 '25_Portfolios_ME_Prior_1_0',
 '25_Portfolios_ME_Prior_1_0_Daily',
 '10_Portfolios_Prior_1_0',
 '10_Portfolios_Prior_1_0_Daily',
 'F-F_LT_Reversal_Factor',
 'F-F_LT_Reversal_Factor_daily',
 '6_Portfolios_ME_Prior_60_13',
 '6_Portfolios_ME_Prior_60_13_Daily',
 '25_Portfolios_ME_Prior_60_13',
 '25_Portfolios_ME_Prior_60_13_Daily',
 '10_Portfolios_Prior_60_13',
 '10_Portfolios_Prior_60_13_Daily',
 'Portfolios_Formed_on_AC',
 '25_Portfolios_ME_AC_5x5',
 'Portfolios_Formed_on_BETA',
 '25_Portfolios_ME_BETA_5x5',
 'Portfolios_Formed_on_NI',
 '25_Portfolios_ME_NI_5x5',
 'Portfolios_Formed_on_VAR',
 '25_Portfolios_ME_VAR_5x5',
 'Portfolios_Formed_on_RESVAR',
 '25_Portfolios_ME_RESVAR_5x5',
 '5_Industry_Portfolios',
 '5_Industry_Portfolios_Wout_Div',
 '5_Industry_Portfolios_daily',
 '10_Industry_Portfolios',
 '10_Industry_Portfolios_Wout_Div',
 '10_Industry_Portfolios_daily',
 '12_Industry_Portfolios',
 '12_Industry_Portfolios_Wout_Div',
 '12_Industry_Portfolios_daily',
 '17_Industry_Portfolios',
 '17_Industry_Portfolios_Wout_Div',
 '17_Industry_Portfolios_daily',
 '30_Industry_Portfolios',
 '30_Industry_Portfolios_Wout_Div',
 '30_Industry_Portfolios_daily',
 '38_Industry_Portfolios',
 '38_Industry_Portfolios_Wout_Div',
 '38_Industry_Portfolios_daily',
 '48_Industry_Portfolios',
 '48_Industry_Portfolios_Wout_Div',
 '48_Industry_Portfolios_daily',
 '49_Industry_Portfolios',
 '49_Industry_Portfolios_Wout_Div',
 '49_Industry_Portfolios_daily',
 'ME_Breakpoints',
 'BE-ME_Breakpoints',
 'OP_Breakpoints',
 'INV_Breakpoints',
 'E-P_Breakpoints',
 'CF-P_Breakpoints',
 'D-P_Breakpoints',
 'Prior_2-12_Breakpoints',
 'Developed_3_Factors',
 'Developed_3_Factors_Daily',
 'Developed_ex_US_3_Factors',
 'Developed_ex_US_3_Factors_Daily',
 'Europe_3_Factors',
 'Europe_3_Factors_Daily',
 'Japan_3_Factors',
 'Japan_3_Factors_Daily',
 'Asia_Pacific_ex_Japan_3_Factors',
 'Asia_Pacific_ex_Japan_3_Factors_Daily',
 'North_America_3_Factors',
 'North_America_3_Factors_Daily',
 'Developed_5_Factors',
 'Developed_5_Factors_Daily',
 'Developed_ex_US_5_Factors',
 'Developed_ex_US_5_Factors_Daily',
 'Europe_5_Factors',
 'Europe_5_Factors_Daily',
 'Japan_5_Factors',
 'Japan_5_Factors_Daily',
 'Asia_Pacific_ex_Japan_5_Factors',
 'Asia_Pacific_ex_Japan_5_Factors_Daily',
 'North_America_5_Factors',
 'North_America_5_Factors_Daily',
 'Developed_Mom_Factor',
 'Developed_Mom_Factor_Daily',
 'Developed_ex_US_Mom_Factor',
 'Developed_ex_US_Mom_Factor_Daily',
 'Europe_Mom_Factor',
 'Europe_Mom_Factor_Daily',
 'Japan_Mom_Factor',
 'Japan_Mom_Factor_Daily',
 'Asia_Pacific_ex_Japan_MOM_Factor',
 'Asia_Pacific_ex_Japan_MOM_Factor_Daily',
 'North_America_Mom_Factor',
 'North_America_Mom_Factor_Daily',
 'Developed_6_Portfolios_ME_BE-ME',
 'Developed_6_Portfolios_ME_BE-ME_daily',
 'Developed_ex_US_6_Portfolios_ME_BE-ME',
 'Developed_ex_US_6_Portfolios_ME_BE-ME_daily',
 'Europe_6_Portfolios_ME_BE-ME',
 'Europe_6_Portfolios_ME_BE-ME_daily',
 'Japan_6_Portfolios_ME_BE-ME',
 'Japan_6_Portfolios_ME_BE-ME_daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_daily',
 'North_America_6_Portfolios_ME_BE-ME',
 'North_America_6_Portfolios_ME_BE-ME_daily',
 'Developed_25_Portfolios_ME_BE-ME',
 'Developed_25_Portfolios_ME_BE-ME_daily',
 'Developed_ex_US_25_Portfolios_ME_BE-ME',
 'Developed_ex_US_25_Portfolios_ME_BE-ME_daily',
 'Europe_25_Portfolios_ME_BE-ME',
 'Europe_25_Portfolios_ME_BE-ME_daily',
 'Japan_25_Portfolios_ME_BE-ME',
 'Japan_25_Portfolios_ME_BE-ME_daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_daily',
 'North_America_25_Portfolios_ME_BE-ME',
 'North_America_25_Portfolios_ME_BE-ME_daily',
 'Developed_6_Portfolios_ME_OP',
 'Developed_6_Portfolios_ME_OP_Daily',
 'Developed_ex_US_6_Portfolios_ME_OP',
 'Developed_ex_US_6_Portfolios_ME_OP_Daily',
 'Europe_6_Portfolios_ME_OP',
 'Europe_6_Portfolios_ME_OP_Daily',
 'Japan_6_Portfolios_ME_OP',
 'Japan_6_Portfolios_ME_OP_Daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_OP',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_Daily',
 'North_America_6_Portfolios_ME_OP',
 'North_America_6_Portfolios_ME_OP_Daily',
 'Developed_25_Portfolios_ME_OP',
 'Developed_25_Portfolios_ME_OP_Daily',
 'Developed_ex_US_25_Portfolios_ME_OP',
 'Developed_ex_US_25_Portfolios_ME_OP_Daily',
 'Europe_25_Portfolios_ME_OP',
 'Europe_25_Portfolios_ME_OP_Daily',
 'Japan_25_Portfolios_ME_OP',
 'Japan_25_Portfolios_ME_OP_Daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_OP',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily',
 'North_America_25_Portfolios_ME_OP',
 'North_America_25_Portfolios_ME_OP_Daily',
 'Developed_6_Portfolios_ME_INV',
 'Developed_6_Portfolios_ME_INV_Daily',
 'Developed_ex_US_6_Portfolios_ME_INV',
 'Developed_ex_US_6_Portfolios_ME_INV_Daily',
 'Europe_6_Portfolios_ME_INV',
 'Europe_6_Portfolios_ME_INV_Daily',
 'Japan_6_Portfolios_ME_INV',
 'Japan_6_Portfolios_ME_INV_Daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_INV',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_Daily',
 'North_America_6_Portfolios_ME_INV',
 'North_America_6_Portfolios_ME_INV_Daily',
 'Developed_25_Portfolios_ME_INV',
 'Developed_25_Portfolios_ME_INV_Daily',
 'Developed_ex_US_25_Portfolios_ME_INV',
 'Developed_ex_US_25_Portfolios_ME_INV_Daily',
 'Europe_25_Portfolios_ME_INV',
 'Europe_25_Portfolios_ME_INV_Daily',
 'Japan_25_Portfolios_ME_INV',
 'Japan_25_Portfolios_ME_INV_Daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_INV',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_Daily',
 'North_America_25_Portfolios_ME_INV',
 'North_America_25_Portfolios_ME_INV_Daily',
 'Developed_6_Portfolios_ME_Prior_12_2',
 'Developed_6_Portfolios_ME_Prior_250_20_daily',
 'Developed_ex_US_6_Portfolios_ME_Prior_12_2',
 'Developed_ex_US_6_Portfolios_ME_Prior_250_20_daily',
 'Europe_6_Portfolios_ME_Prior_12_2',
 'Europe_6_Portfolios_ME_Prior_250_20_daily',
 'Japan_6_Portfolios_ME_Prior_12_2',
 'Japan_6_Portfolios_ME_Prior_250_20_daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_12_2',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_250_20_daily',
 'North_America_6_Portfolios_ME_Prior_12_2',
 'North_America_6_Portfolios_ME_Prior_250_20_daily',
 'Developed_25_Portfolios_ME_Prior_12_2',
 'Developed_25_Portfolios_ME_Prior_250_20_daily',
 'Developed_ex_US_25_Portfolios_ME_Prior_12_2',
 'Developed_ex_US_25_Portfolios_ME_Prior_250_20_daily',
 'Europe_25_Portfolios_ME_Prior_12_2',
 'Europe_25_Portfolios_ME_Prior_250_20_daily',
 'Japan_25_Portfolios_ME_Prior_12_2',
 'Japan_25_Portfolios_ME_Prior_250_20_daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_12_2',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_250_20_daily',
 'North_America_25_Portfolios_ME_Prior_12_2',
 'North_America_25_Portfolios_ME_Prior_250_20_daily',
 'Developed_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Europe_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Japan_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'North_America_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Developed_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Europe_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'North_America_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Developed_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Europe_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'North_America_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Emerging_5_Factors',
 'Emerging_MOM_Factor',
 'Emerging_Markets_6_Portfolios_ME_BE-ME',
 'Emerging_Markets_6_Portfolios_ME_OP',
 'Emerging_Markets_6_Portfolios_ME_INV',
 'Emerging_Markets_6_Portfolios_ME_Prior_12_2',
 'Emerging_Markets_4_Portfolios_BE-ME_OP',
 'Emerging_Markets_4_Portfolios_OP_INV',
 'Emerging_Markets_4_Portfolios_BE-ME_INV']

In [3]:
# Daily 3 Factor
df = pdr.famafrench.FamaFrenchReader('F-F_Research_Data_Factors_daily')

In [4]:
data = df.read()

/var/folders/mr/nzdp38cj3cz3b0gcgyvws4c40000gp/T/ipykernel_57117/1535062722.py:1: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  data = df.read()

In [5]:
data

{0:             Mkt-RF   SMB   HML    RF
 Date
 2021-04-14   -0.34  0.79  1.41  0.00
 2021-04-15    1.06 -0.44 -1.19  0.00
 2021-04-16    0.27 -0.36  0.65  0.00
 2021-04-19   -0.72 -0.78  0.79  0.00
 2021-04-20   -0.93 -1.18 -1.57  0.00
 ...            ...   ...   ...   ...
 2026-02-23   -1.18 -0.30 -1.31  0.01
 2026-02-24    0.83  0.51 -0.66  0.01
 2026-02-25    0.79 -0.37  0.49  0.01
 2026-02-26   -0.47  0.63  0.32  0.01
 2026-02-27   -0.51 -0.44 -1.25  0.01

 [1225 rows x 4 columns],
 'DESCR': 'F-F Research Data Factors daily\n-------------------------------\n\nThis file was created by using the 202602 CRSP database. The Tbill return is the simple daily rate that, over the number of trading days compounds to 1-month TBill rate. The 1-month TBill rate data until 202405 are from Ibbotson Associates. Starting from 202406, the 1-month TBill rate is from ICE BofA US 1-Month Treasury Bill Index. Copyright 2026 Eugene F. Fama and Kenneth R. French\n\n  0 : (1225 rows x 4 cols)'}

In [6]:
data[0]

            Mkt-RF   SMB   HML    RF
Date
2021-04-14   -0.34  0.79  1.41  0.00
2021-04-15    1.06 -0.44 -1.19  0.00
2021-04-16    0.27 -0.36  0.65  0.00
2021-04-19   -0.72 -0.78  0.79  0.00
2021-04-20   -0.93 -1.18 -1.57  0.00
...            ...   ...   ...   ...
2026-02-23   -1.18 -0.30 -1.31  0.01
2026-02-24    0.83  0.51 -0.66  0.01
2026-02-25    0.79 -0.37  0.49  0.01
2026-02-26   -0.47  0.63  0.32  0.01
2026-02-27   -0.51 -0.44 -1.25  0.01

[1225 rows x 4 columns]

In [7]:
AAPL = yfinance.Ticker("NVDA")

In [8]:
AAPL.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation operates as a data center scale AI infrastructure company. The company operates through two segments, Compute & Networking, and Graphics segments. The Compute & Networking segment provides data center accelerated computing and networking platforms and artificial intelligence solutions and software, and automotive platforms and autonomous and electric vehicle solutions, including software. The Graphics segment offers GeForce GPUs for gaming and PCs; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics. The company's products are used in gaming, professional visualization, data center, and automotive markets. The company sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants worldwide. It has a collaboration with Tech Mahindra Limited to develop artificial intelligence powered telco network operations reasoning agent. The company has a strategic partnership with Lumentum Holdings Inc. to develop optics technologies for AI and data centers. It also has a strategic partnership with Nebius Group N.V. to develop and deploy hyperscale cloud for the artificial intelligence market. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 42000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 62,
   'title': 'Co-Founder, CEO & Director',
   'yearBorn': 1963,
   'fiscalYear': 2025,
   'totalPay': 11054945,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 58,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1512641,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 70,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 1379071,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter J.D.',
   'age': 58,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1362989,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 70,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 2313851,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2025,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 56,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 64,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Toshiya  Hari',
   'title': 'Vice President of Investor Relations & Strategic Finance',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mylene  Mangalindan',
   'title': 'Vice President of Corporate Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 9,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1775001600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 188.745,
 'open': 186.03,
 'dayLow': 185.74,
 'dayHigh': 189.645,
 'regularMarketPreviousClose': 188.745,
 'regularMarketOpen': 186.03,
 'regularMarketDayLow': 185.74,
 'regularMarketDayHigh': 189.645,
 'dividendRate': 0.04,
 'dividendYield': 0.02,
 'exDividendDate': 1773187200,
 'payoutRatio': 0.0082,
 'fiveYearAvgDividendYield': 0.05,
 'beta': 2.335,
 'trailingPE': 38.634693,
 'forwardPE': 17.02987,
 'volume': 126932852,
 'regularMarketVolume': 126932852,
 'averageVolume': 179606693,
 'averageVolume10days': 158365610,
 'averageDailyVolume10Day': 158365610,
 'bid': 187.51,
 'ask': 190.0,
 'bidSize': 90,
 'askSize': 1,
 'marketCap': 4601179799552,
 'nonDilutedMarketCap': 4583709000000,
 'fiftyTwoWeekLow': 95.04,
 'fiftyTwoWeekHigh': 212.19,
 'allTimeHigh': 212.19,
 'allTimeLow': 0.033333,
 'priceToSalesTrailing12Months': 21.307875,
 'fiftyDayAverage': 182.0778,
 'twoHundredDayAverage': 180.7419,
 'trailingAnnualDividendRate': 0.04,
 'trailingAnnualDividendYield': 0.00021192615,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4532565180416,
 'profitMargins': 0.55603004,
 'floatShares': 23321925000,
 'sharesOutstanding': 24300000000,
 'sharesShort': 229241850,
 'sharesShortPriorMonth': 254311707,
 'sharesShortPreviousMonthDate': 1770940800,
 'dateShortInterest': 1773360000,
 'sharesPercentSharesOut': 0.0094,
 'heldPercentInsiders': 0.04212,
 'heldPercentInstitutions': 0.69736,
 'shortRatio': 1.28,
 'shortPercentOfFloat': 0.0098,
 'impliedSharesOutstanding': 24305000000,
 'bookValue': 6.472,
 'priceToBook': 29.250618,
 'lastFiscalYearEnd': 1769299200,
 'nextFiscalYearEnd': 1800835200,
 'mostRecentQuarter': 1769299200,
 'earningsQuarterlyGrowth': 0.945,
 'netIncomeToCommon': 120066998272,
 'trailingEps': 4.9,
 'forwardEps': 11.11635,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 20.99,
 'enterpriseToEbitda': 34.021,
 '52WeekChange': 0.7038208,
 'SandP52WeekChange': 0.26099288,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1773187200,
 'quoteType': 'EQUITY',
 'currentPrice': 189.31,
 'targetHighPrice': 380.0,
 'targetLowPrice': 140.0,
 'targetMeanPrice': 268.22195,
 'targetMedianPrice': 265.0,
 'recommendationMean': 1.28333,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 56,
 'totalCash': 62556000256,
 'totalCashPerShare': 2.574,
 'ebitda': 133230002176,
 'totalDebt': 11411999744,
 'quickRatio': 3.141,
 'currentRatio': 3.905,
 'totalRevenue': 215938007040,
 'debtToEquity': 7.255,
 'revenuePerShare': 8.865,
 'returnOnAssets': 0.51188,
 'returnOnEquity': 1.01485,
 'grossProfits': 153462996992,
 'freeCashflow': 58128998400,
 'operatingCashflow': 102717997056,
 'earningsGrowth': 0.956,
 'revenueGrowth': 0.732,
 'grossMargins': 0.71068,
 'ebitdaMargins': 0.61698,
 'operatingMargins': 0.65024,
 'financialCurrency': 'USD',
 'symbol': 'NVDA',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'prevName': 'Usual Stablecoin',
 'nameChangeDate': '2026-04-13',
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'marketState': 'POST',
 'postMarketChangePercent': -0.021125818,
 'postMarketPrice': 189.27,
 'postMarketChange': -0.039993286,
 'regularMarketChange': 0.56500244,
 'regularMarketDayRange': '185.74 - 189.645',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 179606693,
 'fiftyTwoWeekLowChange': 94.27,
 'fiftyTwoWeekLowChangePercent': 0.9918981,
 'fiftyTwoWeekRange': '95.04 - 212.19',
 'fiftyTwoWeekHighChange': -22.880005,
 'fiftyTwoWeekHighChangePercent': -0.10782791,
 'fiftyTwoWeekChangePercent': 70.38208,
 'dividendDate': 1775001600,
 'earningsTimestamp': 1779307200,
 'earningsTimestampStart': 1779307200,
 'earningsTimestampEnd': 1779307200,
 'earningsCallTimestampStart': 1772056800,
 'earningsCallTimestampEnd': 1772056800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 4.9,
 'epsForward': 11.11635,
 'epsCurrentYear': 8.29457,
 'priceEpsCurrentYear': 22.823364,
 'fiftyDayAverageChange': 7.232193,
 'fiftyDayAverageChangePercent': 0.039720345,
 'twoHundredDayAverageChange': 8.5681,
 'twoHundredDayAverageChangePercent': 0.04740517,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 917015400000,
 'regularMarketChangePercent': 0.29934698,
 'regularMarketPrice': 189.31,
 'corporateActions': [],
 'postMarketTime': 1776111787,
 'regularMarketTime': 1776110400,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_32307',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'displayName': 'NVIDIA',
 'trailingPegRatio': 0.7664}

In [9]:
AAPL.info['symbol']

'NVDA'

In [10]:
history = AAPL.history(period='5y')

In [11]:
history = history.reset_index()

In [12]:
history['Date'] = history['Date'].dt.date

In [13]:
history

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-04-14,15.585719,15.680979,15.189218,15.238594,385500000,0.0,0.0
1,2021-04-15,15.623125,16.173488,15.592202,16.096682,598480000,0.0,0.0
2,2021-04-16,16.012641,16.125108,15.825363,15.872495,335208000,0.0,0.0
3,2021-04-19,15.497440,15.767758,15.194703,15.323129,404420000,0.0,0.0
4,2021-04-20,15.284725,15.458039,14.925382,15.133108,334132000,0.0,0.0
...,...,...,...,...,...,...,...,...
1250,2026-04-07,175.729996,178.229996,173.660004,178.100006,132534900,0.0,0.0
1251,2026-04-08,184.500000,185.259995,180.300003,182.080002,147732700,0.0,0.0
1252,2026-04-09,181.839996,184.080002,180.619995,183.910004,116428500,0.0,0.0
1253,2026-04-10,184.309998,190.000000,184.300003,188.630005,160099500,0.0,0.0
1254,2026-04-13,186.029999,189.649994,185.740005,189.309998,126951527,0.0,0.0

In [14]:
history['Previous Close'] = history['Close'].shift(1)

In [15]:
history['Percentage Change'] = ((history['Close'] - history['Previous Close']) / history['Previous Close']) * 100

In [16]:
history = history.dropna()

In [17]:
condensed_history = history[['Date', 'Percentage Change']]

In [18]:
condensed_history

            Date  Percentage Change
1     2021-04-15           5.631015
2     2021-04-16          -1.392752
3     2021-04-19          -3.461119
4     2021-04-20          -1.240090
5     2021-04-21           1.247437
...          ...                ...
1250  2026-04-07           0.258954
1251  2026-04-08           2.234697
1252  2026-04-09           1.005054
1253  2026-04-10           2.566473
1254  2026-04-13           0.360490

[1254 rows x 2 columns]

In [19]:
Fama_3_Factor = data[0].reset_index()

In [20]:
Fama_3_Factor['Date'] = Fama_3_Factor['Date'].dt.date

In [21]:
Fama_3_Factor

            Date  Mkt-RF   SMB   HML    RF
0     2021-04-14   -0.34  0.79  1.41  0.00
1     2021-04-15    1.06 -0.44 -1.19  0.00
2     2021-04-16    0.27 -0.36  0.65  0.00
3     2021-04-19   -0.72 -0.78  0.79  0.00
4     2021-04-20   -0.93 -1.18 -1.57  0.00
...          ...     ...   ...   ...   ...
1220  2026-02-23   -1.18 -0.30 -1.31  0.01
1221  2026-02-24    0.83  0.51 -0.66  0.01
1222  2026-02-25    0.79 -0.37  0.49  0.01
1223  2026-02-26   -0.47  0.63  0.32  0.01
1224  2026-02-27   -0.51 -0.44 -1.25  0.01

[1225 rows x 5 columns]

In [22]:
Combined = Fama_3_Factor.merge(condensed_history, on='Date', how='inner')

In [23]:
Combined

            Date  Mkt-RF   SMB   HML    RF  Percentage Change
0     2021-04-15    1.06 -0.44 -1.19  0.00           5.631015
1     2021-04-16    0.27 -0.36  0.65  0.00          -1.392752
2     2021-04-19   -0.72 -0.78  0.79  0.00          -3.461119
3     2021-04-20   -0.93 -1.18 -1.57  0.00          -1.240090
4     2021-04-21    1.10  1.38  0.12  0.00           1.247437
...          ...     ...   ...   ...   ...                ...
1219  2026-02-23   -1.18 -0.30 -1.31  0.01           0.911389
1220  2026-02-24    0.83  0.51 -0.66  0.01           0.678672
1221  2026-02-25    0.79 -0.37  0.49  0.01           1.405230
1222  2026-02-26   -0.47  0.63  0.32  0.01          -5.456124
1223  2026-02-27   -0.51 -0.44 -1.25  0.01          -4.164631

[1224 rows x 6 columns]

In [24]:
Combined['Percent Change minus RF'] = (Combined['Percentage Change'] - (Combined['RF']))

In [25]:
Combined = Combined.drop(columns = 'Percentage Change')

In [26]:
Combined.columns

Index(['Date', 'Mkt-RF', 'SMB', 'HML', 'RF', 'Percent Change minus RF'], dtype='object')

In [27]:
tscv = TimeSeriesSplit(n_splits=4, test_size=252, gap=5)

X = Combined[['Mkt-RF', 'SMB', 'HML']]
y = Combined[['Percent Change minus RF']]

split_data = []

for i, (train_index, test_index) in enumerate(tscv.split(Combined)):
    train_dates = Combined.iloc[train_index]['Date']
    test_dates = Combined.iloc[test_index]['Date']

    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and Fit
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    residuals = y_test - y_pred

    # Check your Factor Loadings (Betas) for this fold
    print(f"Mkt-RF Beta: {model.coef_[0]}")
    print(f"Alpha (Intercept): {model.intercept_}")
    print(f"R2 score: {model.score(X_test, y_test)}")
    # If the average residual is positive, the stock outperformed the model's expectations
    print(f"Mean Prediction Error: {residuals.mean()}")
    X_train_with_const = sm.add_constant(X_train)

    mse_val = mean_squared_error(y_test, y_pred)
    rmse_val = np.sqrt(mse_val)

    # 2. Fit the OLS (Ordinary Least Squares) model
    ols_model = sm.OLS(y_train, X_train_with_const).fit()

    # 3. Access the p-values
    p_values = ols_model.pvalues
    print(f"P-values for this fold:\n{p_values}")

    # 4. View the full academic summary
    print(ols_model.summary())
    
    # 4. Store metrics in a dictionary
    fold_result = {
        'Fold': i + 1,
        'Period_Start': test_dates.min(),
        'Period_End': test_dates.max(),
        # Accuracy Metrics
        'In_Sample_R2': ols_model.rsquared,
        'Out_of_Sample_R2': model.score(X_test, y_test),
        'RMSE': rmse_val,
        'Mean Prediciton Error': residuals.mean(),
        # Coefficients (Betas)
        'Alpha': ols_model.params['const'],
        'Mkt_Beta': ols_model.params['Mkt-RF'],
        'SMB_Beta': ols_model.params['SMB'],
        'HML_Beta': ols_model.params['HML'],
        # P-Values (Is it significant?)
        'Alpha_P': ols_model.pvalues['const'],
        'Mkt_P': ols_model.pvalues['Mkt-RF'],
        'SMB_P': ols_model.pvalues['SMB'],
        'HML_P': ols_model.pvalues['HML']
    }
    
    split_data.append(fold_result)

Mkt-RF Beta: [ 1.95148438 -0.14069482 -0.91334307]
Alpha (Intercept): [0.29910372]
R2 score: 0.7313143229655948
Mean Prediction Error: Percent Change minus RF   -0.211606
dtype: float64
P-values for this fold:
const     2.428251e-02
Mkt-RF    2.706357e-26
SMB       4.714399e-01
HML       1.669461e-12
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.584
Model:                                 OLS   Adj. R-squared:                  0.578
Method:                      Least Squares   F-statistic:                     96.76
Date:                     Mon, 13 Apr 2026   Prob (F-statistic):           3.55e-39
Time:                             15:23:12   Log-Likelihood:                -432.19
No. Observations:                      211   AIC:                             872.4
Df Residuals:                          207   BIC:                             885.8
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2991      0.132      2.269      0.024       0.039       0.559
Mkt-RF         1.9515      0.159     12.247      0.000       1.637       2.266
SMB           -0.1407      0.195     -0.721      0.471      -0.525       0.244
HML           -0.9133      0.122     -7.517      0.000      -1.153      -0.674
==============================================================================
Omnibus:                       51.777   Durbin-Watson:                   2.072
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              185.093
Skew:                           0.942   Prob(JB):                     6.42e-41
Kurtosis:                       7.183   Cond. No.                         1.95
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mkt-RF Beta: [ 1.84093489  0.01554751 -0.8336525 ]
Alpha (Intercept): [0.19596258]
R2 score: 0.33553202774982116
Mean Prediction Error: Percent Change minus RF    0.167973
dtype: float64
P-values for this fold:
const     3.304506e-02
Mkt-RF    1.646784e-78
SMB       9.167376e-01
HML       1.361555e-17
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.694
Model:                                 OLS   Adj. R-squared:                  0.692
Method:                      Least Squares   F-statistic:                     346.3
Date:                     Mon, 13 Apr 2026   Prob (F-statistic):          1.83e-117
Time:                             15:23:12   Log-Likelihood:                -968.60
No. Observations:                      463   AIC:                             1945.
Df Residuals:                          459   BIC:                             1962.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1960      0.092      2.138      0.033       0.016       0.376
Mkt-RF         1.8409      0.080     23.017      0.000       1.684       1.998
SMB            0.0155      0.149      0.105      0.917      -0.277       0.308
HML           -0.8337      0.094     -8.894      0.000      -1.018      -0.649
==============================================================================
Omnibus:                       40.316   Durbin-Watson:                   1.970
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              157.290
Skew:                           0.250   Prob(JB):                     7.00e-35
Kurtosis:                       5.811   Cond. No.                         2.53
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mkt-RF Beta: [ 1.87623909 -0.26593744 -0.89879795]
Alpha (Intercept): [0.23368787]
R2 score: 0.4933623230754812
Mean Prediction Error: Percent Change minus RF   -0.086509
dtype: float64
P-values for this fold:
const     3.235061e-03
Mkt-RF    9.985005e-97
SMB       2.751977e-02
HML       4.706592e-25
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.599
Model:                                 OLS   Adj. R-squared:                  0.598
Method:                      Least Squares   F-statistic:                     354.6
Date:                     Mon, 13 Apr 2026   Prob (F-statistic):          9.93e-141
Time:                             15:23:12   Log-Likelihood:                -1547.0
No. Observations:                      715   AIC:                             3102.
Df Residuals:                          711   BIC:                             3120.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2337      0.079      2.955      0.003       0.078       0.389
Mkt-RF         1.8762      0.077     24.526      0.000       1.726       2.026
SMB           -0.2659      0.120     -2.209      0.028      -0.502      -0.030
HML           -0.8988      0.084    -10.744      0.000      -1.063      -0.735
==============================================================================
Omnibus:                      389.892   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10241.610
Skew:                           1.905   Prob(JB):                         0.00
Kurtosis:                      21.146   Cond. No.                         2.06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mkt-RF Beta: [ 1.98592533 -0.44847843 -1.03232492]
Alpha (Intercept): [0.20841288]
R2 score: 0.6558380595012387
Mean Prediction Error: Percent Change minus RF   -0.138313
dtype: float64
P-values for this fold:
const      3.690315e-03
Mkt-RF    2.992400e-118
SMB        3.571106e-05
HML        1.448763e-35
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.572
Model:                                 OLS   Adj. R-squared:                  0.571
Method:                      Least Squares   F-statistic:                     429.7
Date:                     Mon, 13 Apr 2026   Prob (F-statistic):          4.11e-177
Time:                             15:23:12   Log-Likelihood:                -2141.9
No. Observations:                      967   AIC:                             4292.
Df Residuals:                          963   BIC:                             4311.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2084      0.072      2.911      0.004       0.068       0.349
Mkt-RF         1.9859      0.074     26.739      0.000       1.840       2.132
SMB           -0.4485      0.108     -4.153      0.000      -0.660      -0.237
HML           -1.0323      0.080    -12.969      0.000      -1.189      -0.876
==============================================================================
Omnibus:                      345.892   Durbin-Watson:                   2.077
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5843.000
Skew:                           1.177   Prob(JB):                         0.00
Kurtosis:                      14.810   Cond. No.                         1.93
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [28]:
# Convert to DataFrame for the Stability Report
stability_df = pd.DataFrame(split_data)

In [29]:
stability_df

,Fold,Period_Start,Period_End,In_Sample_R2,Out_of_Sample_R2,RMSE,Mean Prediciton Error,Alpha,Mkt_Beta,SMB_Beta,HML_Beta,Alpha_P,Mkt_P,SMB_P,HML_P
0,1,2022-02-22,2023-02-22,0.583740,0.731314,2.037606,Percent Change minus RF -0.211606 dtype: flo...,0.299104,1.951484,-0.140695,-0.913343,0.024283,2.706357e-26,0.471440,1.669461e-12
1,2,2023-02-23,2024-02-23,0.693583,0.335532,2.480088,Percent Change minus RF 0.167973 dtype: flo...,0.195963,1.840935,0.015548,-0.833653,0.033045,1.646784e-78,0.916738,1.361555e-17
2,3,2024-02-26,2025-02-26,0.599360,0.493362,2.439094,Percent Change minus RF -0.086509 dtype: flo...,0.233688,1.876239,-0.265937,-0.898798,0.003235,9.985005e-97,0.027520,4.706592e-25
3,4,2025-02-27,2026-02-27,0.572409,0.655838,1.641227,Percent Change minus RF -0.138313 dtype: flo...,0.208413,1.985925,-0.448478,-1.032325,0.003690,2.992400e-118,0.000036,1.448763e-35

In [30]:

X_full = Combined[['Mkt-RF', 'SMB', 'HML']]
y_full = Combined['Percent Change minus RF']

X_full_const = sm.add_constant(X_full)


final_model = sm.OLS(y_full, X_full_const).fit()

# 4. Display the results for your dashboard
print(final_model.summary())

# Extracting values from the final_model object
results_summary = {
    'Ticker': AAPL.info['symbol'],
    'Name': AAPL.info['shortName'],
    'Industry': AAPL.info['industry'],
    'Summary': AAPL.info['longBusinessSummary'],
    'Current_Alpha': final_model.params['const'],
    'Market_Beta': final_model.params['Mkt-RF'],
    'Size_Beta': final_model.params['SMB'],
    'Value_Beta': final_model.params['HML'],
    'Alpha_PValue': final_model.pvalues['const'],
    'Overall_Fit': final_model.rsquared_adj,
    'Lower_Alpha_Bound': final_model.conf_int().loc['const', 0],
    'Upper_Alpha_Bound': final_model.conf_int().loc['const', 1]
}

                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.587
Model:                                 OLS   Adj. R-squared:                  0.586
Method:                      Least Squares   F-statistic:                     577.1
Date:                     Mon, 13 Apr 2026   Prob (F-statistic):          2.03e-233
Time:                             15:23:12   Log-Likelihood:                -2648.7
No. Observations:                     1224   AIC:                             5305.
Df Residuals:                         1220   BIC:                             5326.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1856      0.060      3.070      0.002       0.067       0.304
Mkt-RF         1.8884      0.061     30.906      0.000       1.768       2.008
SMB           -0.4481      0.092     -4.860      0.000      -0.629      -0.267
HML           -1.0709      0.070    -15.203      0.000      -1.209      -0.933
==============================================================================
Omnibus:                      417.130   Durbin-Watson:                   2.063
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7273.842
Skew:                           1.109   Prob(JB):                         0.00
Kurtosis:                      14.735   Cond. No.                         1.95
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
# Daily 3 Factor
fivef_df = pdr.famafrench.FamaFrenchReader('F-F_Research_Data_5_Factors_2x3_daily')

In [32]:
fivef_df[0]

TypeError: 'FamaFrenchReader' object is not subscriptable