In [36]:
# Import Dependencies
import yfinance
import pandas_datareader as pdr
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
pdr.famafrench.get_available_datasets()

['F-F_Research_Data_Factors',
 'F-F_Research_Data_Factors_weekly',
 'F-F_Research_Data_Factors_daily',
 'F-F_Research_Data_5_Factors_2x3',
 'F-F_Research_Data_5_Factors_2x3_daily',
 'Portfolios_Formed_on_ME',
 'Portfolios_Formed_on_ME_Wout_Div',
 'Portfolios_Formed_on_ME_Daily',
 'Portfolios_Formed_on_BE-ME',
 'Portfolios_Formed_on_BE-ME_Wout_Div',
 'Portfolios_Formed_on_BE-ME_Daily',
 'Portfolios_Formed_on_OP',
 'Portfolios_Formed_on_OP_Wout_Div',
 'Portfolios_Formed_on_OP_Daily',
 'Portfolios_Formed_on_INV',
 'Portfolios_Formed_on_INV_Wout_Div',
 'Portfolios_Formed_on_INV_Daily',
 '6_Portfolios_2x3',
 '6_Portfolios_2x3_Wout_Div',
 '6_Portfolios_2x3_weekly',
 '6_Portfolios_2x3_daily',
 '25_Portfolios_5x5',
 '25_Portfolios_5x5_Wout_Div',
 '25_Portfolios_5x5_Daily',
 '100_Portfolios_10x10',
 '100_Portfolios_10x10_Wout_Div',
 '100_Portfolios_10x10_Daily',
 '6_Portfolios_ME_OP_2x3',
 '6_Portfolios_ME_OP_2x3_Wout_Div',
 '6_Portfolios_ME_OP_2x3_daily',
 '25_Portfolios_ME_OP_5x5',
 '25_Portfolios_ME_OP_5x5_Wout_Div',
 '25_Portfolios_ME_OP_5x5_daily',
 '100_Portfolios_ME_OP_10x10',
 '100_Portfolios_10x10_ME_OP_Wout_Div',
 '100_Portfolios_ME_OP_10x10_daily',
 '6_Portfolios_ME_INV_2x3',
 '6_Portfolios_ME_INV_2x3_Wout_Div',
 '6_Portfolios_ME_INV_2x3_daily',
 '25_Portfolios_ME_INV_5x5',
 '25_Portfolios_ME_INV_5x5_Wout_Div',
 '25_Portfolios_ME_INV_5x5_daily',
 '100_Portfolios_ME_INV_10x10',
 '100_Portfolios_10x10_ME_INV_Wout_Div',
 '100_Portfolios_ME_INV_10x10_daily',
 '25_Portfolios_BEME_OP_5x5',
 '25_Portfolios_BEME_OP_5x5_Wout_Div',
 '25_Portfolios_BEME_OP_5x5_daily',
 '25_Portfolios_BEME_INV_5x5',
 '25_Portfolios_BEME_INV_5x5_Wout_Div',
 '25_Portfolios_BEME_INV_5x5_daily',
 '25_Portfolios_OP_INV_5x5',
 '25_Portfolios_OP_INV_5x5_Wout_Div',
 '25_Portfolios_OP_INV_5x5_daily',
 '32_Portfolios_ME_BEME_OP_2x4x4',
 '32_Portfolios_ME_BEME_OP_2x4x4_Wout_Div',
 '32_Portfolios_ME_BEME_INV_2x4x4',
 '32_Portfolios_ME_BEME_INV_2x4x4_Wout_Div',
 '32_Portfolios_ME_OP_INV_2x4x4',
 '32_Portfolios_ME_OP_INV_2x4x4_Wout_Div',
 'Portfolios_Formed_on_E-P',
 'Portfolios_Formed_on_E-P_Wout_Div',
 'Portfolios_Formed_on_CF-P',
 'Portfolios_Formed_on_CF-P_Wout_Div',
 'Portfolios_Formed_on_D-P',
 'Portfolios_Formed_on_D-P_Wout_Div',
 '6_Portfolios_ME_EP_2x3',
 '6_Portfolios_ME_EP_2x3_Wout_Div',
 '6_Portfolios_ME_CFP_2x3',
 '6_Portfolios_ME_CFP_2x3_Wout_Div',
 '6_Portfolios_ME_DP_2x3',
 '6_Portfolios_ME_DP_2x3_Wout_Div',
 'F-F_Momentum_Factor',
 'F-F_Momentum_Factor_daily',
 '6_Portfolios_ME_Prior_12_2',
 '6_Portfolios_ME_Prior_12_2_Daily',
 '25_Portfolios_ME_Prior_12_2',
 '25_Portfolios_ME_Prior_12_2_Daily',
 '10_Portfolios_Prior_12_2',
 '10_Portfolios_Prior_12_2_Daily',
 'F-F_ST_Reversal_Factor',
 'F-F_ST_Reversal_Factor_daily',
 '6_Portfolios_ME_Prior_1_0',
 '6_Portfolios_ME_Prior_1_0_Daily',
 '25_Portfolios_ME_Prior_1_0',
 '25_Portfolios_ME_Prior_1_0_Daily',
 '10_Portfolios_Prior_1_0',
 '10_Portfolios_Prior_1_0_Daily',
 'F-F_LT_Reversal_Factor',
 'F-F_LT_Reversal_Factor_daily',
 '6_Portfolios_ME_Prior_60_13',
 '6_Portfolios_ME_Prior_60_13_Daily',
 '25_Portfolios_ME_Prior_60_13',
 '25_Portfolios_ME_Prior_60_13_Daily',
 '10_Portfolios_Prior_60_13',
 '10_Portfolios_Prior_60_13_Daily',
 'Portfolios_Formed_on_AC',
 '25_Portfolios_ME_AC_5x5',
 'Portfolios_Formed_on_BETA',
 '25_Portfolios_ME_BETA_5x5',
 'Portfolios_Formed_on_NI',
 '25_Portfolios_ME_NI_5x5',
 'Portfolios_Formed_on_VAR',
 '25_Portfolios_ME_VAR_5x5',
 'Portfolios_Formed_on_RESVAR',
 '25_Portfolios_ME_RESVAR_5x5',
 '5_Industry_Portfolios',
 '5_Industry_Portfolios_Wout_Div',
 '5_Industry_Portfolios_daily',
 '10_Industry_Portfolios',
 '10_Industry_Portfolios_Wout_Div',
 '10_Industry_Portfolios_daily',
 '12_Industry_Portfolios',
 '12_Industry_Portfolios_Wout_Div',
 '12_Industry_Portfolios_daily',
 '17_Industry_Portfolios',
 '17_Industry_Portfolios_Wout_Div',
 '17_Industry_Portfolios_daily',
 '30_Industry_Portfolios',
 '30_Industry_Portfolios_Wout_Div',
 '30_Industry_Portfolios_daily',
 '38_Industry_Portfolios',
 '38_Industry_Portfolios_Wout_Div',
 '38_Industry_Portfolios_daily',
 '48_Industry_Portfolios',
 '48_Industry_Portfolios_Wout_Div',
 '48_Industry_Portfolios_daily',
 '49_Industry_Portfolios',
 '49_Industry_Portfolios_Wout_Div',
 '49_Industry_Portfolios_daily',
 'ME_Breakpoints',
 'BE-ME_Breakpoints',
 'OP_Breakpoints',
 'INV_Breakpoints',
 'E-P_Breakpoints',
 'CF-P_Breakpoints',
 'D-P_Breakpoints',
 'Prior_2-12_Breakpoints',
 'Developed_3_Factors',
 'Developed_3_Factors_Daily',
 'Developed_ex_US_3_Factors',
 'Developed_ex_US_3_Factors_Daily',
 'Europe_3_Factors',
 'Europe_3_Factors_Daily',
 'Japan_3_Factors',
 'Japan_3_Factors_Daily',
 'Asia_Pacific_ex_Japan_3_Factors',
 'Asia_Pacific_ex_Japan_3_Factors_Daily',
 'North_America_3_Factors',
 'North_America_3_Factors_Daily',
 'Developed_5_Factors',
 'Developed_5_Factors_Daily',
 'Developed_ex_US_5_Factors',
 'Developed_ex_US_5_Factors_Daily',
 'Europe_5_Factors',
 'Europe_5_Factors_Daily',
 'Japan_5_Factors',
 'Japan_5_Factors_Daily',
 'Asia_Pacific_ex_Japan_5_Factors',
 'Asia_Pacific_ex_Japan_5_Factors_Daily',
 'North_America_5_Factors',
 'North_America_5_Factors_Daily',
 'Developed_Mom_Factor',
 'Developed_Mom_Factor_Daily',
 'Developed_ex_US_Mom_Factor',
 'Developed_ex_US_Mom_Factor_Daily',
 'Europe_Mom_Factor',
 'Europe_Mom_Factor_Daily',
 'Japan_Mom_Factor',
 'Japan_Mom_Factor_Daily',
 'Asia_Pacific_ex_Japan_MOM_Factor',
 'Asia_Pacific_ex_Japan_MOM_Factor_Daily',
 'North_America_Mom_Factor',
 'North_America_Mom_Factor_Daily',
 'Developed_6_Portfolios_ME_BE-ME',
 'Developed_6_Portfolios_ME_BE-ME_daily',
 'Developed_ex_US_6_Portfolios_ME_BE-ME',
 'Developed_ex_US_6_Portfolios_ME_BE-ME_daily',
 'Europe_6_Portfolios_ME_BE-ME',
 'Europe_6_Portfolios_ME_BE-ME_daily',
 'Japan_6_Portfolios_ME_BE-ME',
 'Japan_6_Portfolios_ME_BE-ME_daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_daily',
 'North_America_6_Portfolios_ME_BE-ME',
 'North_America_6_Portfolios_ME_BE-ME_daily',
 'Developed_25_Portfolios_ME_BE-ME',
 'Developed_25_Portfolios_ME_BE-ME_daily',
 'Developed_ex_US_25_Portfolios_ME_BE-ME',
 'Developed_ex_US_25_Portfolios_ME_BE-ME_daily',
 'Europe_25_Portfolios_ME_BE-ME',
 'Europe_25_Portfolios_ME_BE-ME_daily',
 'Japan_25_Portfolios_ME_BE-ME',
 'Japan_25_Portfolios_ME_BE-ME_daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_daily',
 'North_America_25_Portfolios_ME_BE-ME',
 'North_America_25_Portfolios_ME_BE-ME_daily',
 'Developed_6_Portfolios_ME_OP',
 'Developed_6_Portfolios_ME_OP_Daily',
 'Developed_ex_US_6_Portfolios_ME_OP',
 'Developed_ex_US_6_Portfolios_ME_OP_Daily',
 'Europe_6_Portfolios_ME_OP',
 'Europe_6_Portfolios_ME_OP_Daily',
 'Japan_6_Portfolios_ME_OP',
 'Japan_6_Portfolios_ME_OP_Daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_OP',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_Daily',
 'North_America_6_Portfolios_ME_OP',
 'North_America_6_Portfolios_ME_OP_Daily',
 'Developed_25_Portfolios_ME_OP',
 'Developed_25_Portfolios_ME_OP_Daily',
 'Developed_ex_US_25_Portfolios_ME_OP',
 'Developed_ex_US_25_Portfolios_ME_OP_Daily',
 'Europe_25_Portfolios_ME_OP',
 'Europe_25_Portfolios_ME_OP_Daily',
 'Japan_25_Portfolios_ME_OP',
 'Japan_25_Portfolios_ME_OP_Daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_OP',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily',
 'North_America_25_Portfolios_ME_OP',
 'North_America_25_Portfolios_ME_OP_Daily',
 'Developed_6_Portfolios_ME_INV',
 'Developed_6_Portfolios_ME_INV_Daily',
 'Developed_ex_US_6_Portfolios_ME_INV',
 'Developed_ex_US_6_Portfolios_ME_INV_Daily',
 'Europe_6_Portfolios_ME_INV',
 'Europe_6_Portfolios_ME_INV_Daily',
 'Japan_6_Portfolios_ME_INV',
 'Japan_6_Portfolios_ME_INV_Daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_INV',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_Daily',
 'North_America_6_Portfolios_ME_INV',
 'North_America_6_Portfolios_ME_INV_Daily',
 'Developed_25_Portfolios_ME_INV',
 'Developed_25_Portfolios_ME_INV_Daily',
 'Developed_ex_US_25_Portfolios_ME_INV',
 'Developed_ex_US_25_Portfolios_ME_INV_Daily',
 'Europe_25_Portfolios_ME_INV',
 'Europe_25_Portfolios_ME_INV_Daily',
 'Japan_25_Portfolios_ME_INV',
 'Japan_25_Portfolios_ME_INV_Daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_INV',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_Daily',
 'North_America_25_Portfolios_ME_INV',
 'North_America_25_Portfolios_ME_INV_Daily',
 'Developed_6_Portfolios_ME_Prior_12_2',
 'Developed_6_Portfolios_ME_Prior_250_20_daily',
 'Developed_ex_US_6_Portfolios_ME_Prior_12_2',
 'Developed_ex_US_6_Portfolios_ME_Prior_250_20_daily',
 'Europe_6_Portfolios_ME_Prior_12_2',
 'Europe_6_Portfolios_ME_Prior_250_20_daily',
 'Japan_6_Portfolios_ME_Prior_12_2',
 'Japan_6_Portfolios_ME_Prior_250_20_daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_12_2',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_250_20_daily',
 'North_America_6_Portfolios_ME_Prior_12_2',
 'North_America_6_Portfolios_ME_Prior_250_20_daily',
 'Developed_25_Portfolios_ME_Prior_12_2',
 'Developed_25_Portfolios_ME_Prior_250_20_daily',
 'Developed_ex_US_25_Portfolios_ME_Prior_12_2',
 'Developed_ex_US_25_Portfolios_ME_Prior_250_20_daily',
 'Europe_25_Portfolios_ME_Prior_12_2',
 'Europe_25_Portfolios_ME_Prior_250_20_daily',
 'Japan_25_Portfolios_ME_Prior_12_2',
 'Japan_25_Portfolios_ME_Prior_250_20_daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_12_2',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_250_20_daily',
 'North_America_25_Portfolios_ME_Prior_12_2',
 'North_America_25_Portfolios_ME_Prior_250_20_daily',
 'Developed_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Europe_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Japan_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'North_America_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Developed_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Europe_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'North_America_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Developed_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Europe_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'North_America_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Emerging_5_Factors',
 'Emerging_MOM_Factor',
 'Emerging_Markets_6_Portfolios_ME_BE-ME',
 'Emerging_Markets_6_Portfolios_ME_OP',
 'Emerging_Markets_6_Portfolios_ME_INV',
 'Emerging_Markets_6_Portfolios_ME_Prior_12_2',
 'Emerging_Markets_4_Portfolios_BE-ME_OP',
 'Emerging_Markets_4_Portfolios_OP_INV',
 'Emerging_Markets_4_Portfolios_BE-ME_INV']

In [3]:
# Daily 3 Factor
df = pdr.famafrench.FamaFrenchReader('F-F_Research_Data_Factors_daily')

In [4]:
data = df.read()

/var/folders/mr/nzdp38cj3cz3b0gcgyvws4c40000gp/T/ipykernel_27912/1535062722.py:1: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  data = df.read()

In [5]:
data

{0:             Mkt-RF   SMB   HML    RF
 Date
 2021-04-12   -0.04 -0.60  0.56  0.00
 2021-04-13    0.41 -0.30 -1.60  0.00
 2021-04-14   -0.34  0.79  1.41  0.00
 2021-04-15    1.06 -0.44 -1.19  0.00
 2021-04-16    0.27 -0.36  0.65  0.00
 ...            ...   ...   ...   ...
 2026-02-23   -1.18 -0.30 -1.31  0.01
 2026-02-24    0.83  0.51 -0.66  0.01
 2026-02-25    0.79 -0.37  0.49  0.01
 2026-02-26   -0.47  0.63  0.32  0.01
 2026-02-27   -0.51 -0.44 -1.25  0.01

 [1227 rows x 4 columns],
 'DESCR': 'F-F Research Data Factors daily\n-------------------------------\n\nThis file was created by using the 202602 CRSP database. The Tbill return is the simple daily rate that, over the number of trading days compounds to 1-month TBill rate. The 1-month TBill rate data until 202405 are from Ibbotson Associates. Starting from 202406, the 1-month TBill rate is from ICE BofA US 1-Month Treasury Bill Index. Copyright 2026 Eugene F. Fama and Kenneth R. French\n\n  0 : (1227 rows x 4 cols)'}

In [6]:
data[0]

            Mkt-RF   SMB   HML    RF
Date
2021-04-12   -0.04 -0.60  0.56  0.00
2021-04-13    0.41 -0.30 -1.60  0.00
2021-04-14   -0.34  0.79  1.41  0.00
2021-04-15    1.06 -0.44 -1.19  0.00
2021-04-16    0.27 -0.36  0.65  0.00
...            ...   ...   ...   ...
2026-02-23   -1.18 -0.30 -1.31  0.01
2026-02-24    0.83  0.51 -0.66  0.01
2026-02-25    0.79 -0.37  0.49  0.01
2026-02-26   -0.47  0.63  0.32  0.01
2026-02-27   -0.51 -0.44 -1.25  0.01

[1227 rows x 4 columns]

In [7]:
AAPL = yfinance.Ticker("NVDA")

In [8]:
AAPL.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation operates as a data center scale AI infrastructure company. The company operates through two segments, Compute & Networking, and Graphics segments. The Compute & Networking segment provides data center accelerated computing and networking platforms and artificial intelligence solutions and software, and automotive platforms and autonomous and electric vehicle solutions, including software. The Graphics segment offers GeForce GPUs for gaming and PCs; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics. The company's products are used in gaming, professional visualization, data center, and automotive markets. The company sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants worldwide. It has a collaboration with Tech Mahindra Limited to develop artificial intelligence powered telco network operations reasoning agent. The company has a strategic partnership with Lumentum Holdings Inc. to develop optics technologies for AI and data centers. It also has a strategic partnership with Nebius Group N.V. to develop and deploy hyperscale cloud for the artificial intelligence market. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 42000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 62,
   'title': 'Co-Founder, CEO & Director',
   'yearBorn': 1963,
   'fiscalYear': 2025,
   'totalPay': 11054945,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 58,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1512641,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 70,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 1379071,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter J.D.',
   'age': 58,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1362989,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 70,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 2313851,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2025,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 56,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 64,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Toshiya  Hari',
   'title': 'Vice President of Investor Relations & Strategic Finance',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mylene  Mangalindan',
   'title': 'Vice President of Corporate Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 9,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1775001600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 182.08,
 'open': 181.84,
 'dayLow': 180.6201,
 'dayHigh': 183.96,
 'regularMarketPreviousClose': 182.08,
 'regularMarketOpen': 181.84,
 'regularMarketDayLow': 180.6201,
 'regularMarketDayHigh': 183.96,
 'dividendRate': 0.04,
 'dividendYield': 0.02,
 'exDividendDate': 1773187200,
 'payoutRatio': 0.0082,
 'fiveYearAvgDividendYield': 0.05,
 'beta': 2.335,
 'trailingPE': 37.366325,
 'forwardPE': 16.470783,
 'volume': 78011025,
 'regularMarketVolume': 78011025,
 'averageVolume': 180352446,
 'averageVolume10days': 170577780,
 'averageDailyVolume10Day': 170577780,
 'bid': 182.7,
 'ask': 183.41,
 'bidSize': 1,
 'askSize': 2,
 'marketCap': 4450124038144,
 'nonDilutedMarketCap': 4310577000000,
 'fiftyTwoWeekLow': 94.46,
 'fiftyTwoWeekHigh': 212.19,
 'allTimeHigh': 212.19,
 'allTimeLow': 0.033333,
 'priceToSalesTrailing12Months': 20.608341,
 'fiftyDayAverage': 182.507,
 'twoHundredDayAverage': 179.9853,
 'trailingAnnualDividendRate': 0.04,
 'trailingAnnualDividendYield': 0.00021968364,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4373399994368,
 'profitMargins': 0.55603004,
 'floatShares': 23322168000,
 'sharesOutstanding': 24300000000,
 'sharesShort': 229241850,
 'sharesShortPriorMonth': 254311707,
 'sharesShortPreviousMonthDate': 1770940800,
 'dateShortInterest': 1773360000,
 'sharesPercentSharesOut': 0.0094,
 'heldPercentInsiders': 0.04212,
 'heldPercentInstitutions': 0.69722,
 'shortRatio': 1.28,
 'shortPercentOfFloat': 0.0098,
 'impliedSharesOutstanding': 24305000000,
 'bookValue': 6.472,
 'priceToBook': 28.290327,
 'lastFiscalYearEnd': 1769299200,
 'nextFiscalYearEnd': 1800835200,
 'mostRecentQuarter': 1769299200,
 'earningsQuarterlyGrowth': 0.945,
 'netIncomeToCommon': 120066998272,
 'trailingEps': 4.9,
 'forwardEps': 11.11635,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 20.253,
 'enterpriseToEbitda': 32.826,
 '52WeekChange': 0.8446522,
 'SandP52WeekChange': 0.32693863,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1773187200,
 'quoteType': 'EQUITY',
 'currentPrice': 183.095,
 'targetHighPrice': 380.0,
 'targetLowPrice': 140.0,
 'targetMeanPrice': 268.22195,
 'targetMedianPrice': 265.0,
 'recommendationMean': 1.28333,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 56,
 'totalCash': 62556000256,
 'totalCashPerShare': 2.574,
 'ebitda': 133230002176,
 'totalDebt': 11411999744,
 'quickRatio': 3.141,
 'currentRatio': 3.905,
 'totalRevenue': 215938007040,
 'debtToEquity': 7.255,
 'revenuePerShare': 8.865,
 'returnOnAssets': 0.51188,
 'returnOnEquity': 1.01485,
 'grossProfits': 153462996992,
 'freeCashflow': 58128998400,
 'operatingCashflow': 102717997056,
 'earningsGrowth': 0.956,
 'revenueGrowth': 0.732,
 'grossMargins': 0.71068,
 'ebitdaMargins': 0.61698,
 'operatingMargins': 0.65024,
 'financialCurrency': 'USD',
 'symbol': 'NVDA',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'NVIDIA Corporation',
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'prevName': 'Usual Stablecoin',
 'nameChangeDate': '2026-04-09',
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 917015400000,
 'regularMarketChange': 1.0149994,
 'regularMarketDayRange': '180.6201 - 183.96',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 180352446,
 'fiftyTwoWeekLowChange': 88.635,
 'fiftyTwoWeekLowChangePercent': 0.9383337,
 'fiftyTwoWeekRange': '94.46 - 212.19',
 'fiftyTwoWeekHighChange': -29.095001,
 'fiftyTwoWeekHighChangePercent': -0.13711768,
 'fiftyTwoWeekChangePercent': 84.46522,
 'dividendDate': 1775001600,
 'earningsTimestamp': 1779307200,
 'earningsTimestampStart': 1779307200,
 'earningsTimestampEnd': 1779307200,
 'earningsCallTimestampStart': 1772056800,
 'earningsCallTimestampEnd': 1772056800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 4.9,
 'epsForward': 11.11635,
 'epsCurrentYear': 8.29457,
 'priceEpsCurrentYear': 22.07408,
 'fiftyDayAverageChange': 0.58799744,
 'fiftyDayAverageChangePercent': 0.00322178,
 'twoHundredDayAverageChange': 3.1096954,
 'twoHundredDayAverageChangePercent': 0.017277496,
 'longName': 'NVIDIA Corporation',
 'marketState': 'REGULAR',
 'exchange': 'NMS',
 'messageBoardId': 'finmb_32307',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.5574623,
 'regularMarketPrice': 183.095,
 'corporateActions': [],
 'regularMarketTime': 1775759369,
 'displayName': 'NVIDIA',
 'trailingPegRatio': 0.7207}

In [9]:
history = AAPL.history(period='5y')

In [10]:
history = history.reset_index()

In [11]:
history['Date'] = history['Date'].dt.date

In [12]:
history

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-04-09,14.178263,14.371776,14.139362,14.363795,195172000,0.0,0.0
1,2021-04-12,14.253825,15.313904,14.103704,15.170764,869324000,0.0,0.0
2,2021-04-13,15.193205,15.660527,15.087721,15.640079,676212000,0.0,0.0
3,2021-04-14,15.585715,15.680975,15.189214,15.238590,385500000,0.0,0.0
4,2021-04-15,15.623121,16.173484,15.592199,16.096678,598480000,0.0,0.0
...,...,...,...,...,...,...,...,...
1251,2026-04-02,172.179993,177.490005,171.369995,177.389999,143143200,0.0,0.0
1252,2026-04-06,177.160004,177.789993,175.759995,177.639999,107564300,0.0,0.0
1253,2026-04-07,175.729996,178.229996,173.660004,178.100006,132534900,0.0,0.0
1254,2026-04-08,184.500000,185.259995,180.300003,182.080002,147293100,0.0,0.0
1255,2026-04-09,181.839996,183.960007,180.620102,183.095001,78011025,0.0,0.0

In [13]:
history['Previous Close'] = history['Close'].shift(1)

In [14]:
history['Percentage Change'] = ((history['Close'] - history['Previous Close']) / history['Previous Close']) * 100

In [15]:
history = history.dropna()

In [16]:
condensed_history = history[['Date', 'Percentage Change']]

In [17]:
condensed_history

            Date  Percentage Change
1     2021-04-12           5.618074
2     2021-04-13           3.093546
3     2021-04-14          -2.567048
4     2021-04-15           5.631017
5     2021-04-16          -1.392729
...          ...                ...
1251  2026-04-02           0.933143
1252  2026-04-06           0.140932
1253  2026-04-07           0.258954
1254  2026-04-08           2.234697
1255  2026-04-09           0.557447

[1255 rows x 2 columns]

In [18]:
Fama_3_Factor = data[0].reset_index()

In [19]:
Fama_3_Factor['Date'] = Fama_3_Factor['Date'].dt.date

In [20]:
Fama_3_Factor

            Date  Mkt-RF   SMB   HML    RF
0     2021-04-12   -0.04 -0.60  0.56  0.00
1     2021-04-13    0.41 -0.30 -1.60  0.00
2     2021-04-14   -0.34  0.79  1.41  0.00
3     2021-04-15    1.06 -0.44 -1.19  0.00
4     2021-04-16    0.27 -0.36  0.65  0.00
...          ...     ...   ...   ...   ...
1222  2026-02-23   -1.18 -0.30 -1.31  0.01
1223  2026-02-24    0.83  0.51 -0.66  0.01
1224  2026-02-25    0.79 -0.37  0.49  0.01
1225  2026-02-26   -0.47  0.63  0.32  0.01
1226  2026-02-27   -0.51 -0.44 -1.25  0.01

[1227 rows x 5 columns]

In [21]:
Combined = Fama_3_Factor.merge(condensed_history, on='Date', how='inner')

In [22]:
Combined

            Date  Mkt-RF   SMB   HML    RF  Percentage Change
0     2021-04-12   -0.04 -0.60  0.56  0.00           5.618074
1     2021-04-13    0.41 -0.30 -1.60  0.00           3.093546
2     2021-04-14   -0.34  0.79  1.41  0.00          -2.567048
3     2021-04-15    1.06 -0.44 -1.19  0.00           5.631017
4     2021-04-16    0.27 -0.36  0.65  0.00          -1.392729
...          ...     ...   ...   ...   ...                ...
1222  2026-02-23   -1.18 -0.30 -1.31  0.01           0.911389
1223  2026-02-24    0.83  0.51 -0.66  0.01           0.678672
1224  2026-02-25    0.79 -0.37  0.49  0.01           1.405230
1225  2026-02-26   -0.47  0.63  0.32  0.01          -5.456124
1226  2026-02-27   -0.51 -0.44 -1.25  0.01          -4.164631

[1227 rows x 6 columns]

In [23]:
Combined['Percent Change minus RF'] = (Combined['Percentage Change'] - (Combined['RF']))

In [24]:
Combined = Combined.drop(columns = 'Percentage Change')

In [25]:
Combined.columns

Index(['Date', 'Mkt-RF', 'SMB', 'HML', 'RF', 'Percent Change minus RF'], dtype='object')

In [37]:
tscv = TimeSeriesSplit(n_splits=4, test_size=252, gap=5)

X = Combined[['Mkt-RF', 'SMB', 'HML']]
y = Combined[['Percent Change minus RF']]

for train_index, test_index in tscv.split(Combined):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and Fit
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    residuals = y_test - y_pred

    # Check your Factor Loadings (Betas) for this fold
    print(f"Mkt-RF Beta: {model.coef_[0]}")
    print(f"Alpha (Intercept): {model.intercept_}")
    print(f"R2 score: {model.score(X_test, y_test)}")
    # If the average residual is positive, the stock outperformed the model's expectations
    print(f"Mean Prediction Error: {residuals.mean()}")
    X_train_with_const = sm.add_constant(X_train)

    # 2. Fit the OLS (Ordinary Least Squares) model
    ols_model = sm.OLS(y_train, X_train_with_const).fit()

    # 3. Access the p-values
    p_values = ols_model.pvalues
    print(f"P-values for this fold:\n{p_values}")

    # 4. View the full academic summary
    print(ols_model.summary())

Mkt-RF Beta: [ 1.96497121 -0.18204476 -0.91088991]
Alpha (Intercept): [0.32176428]
R2 score: 0.7300948035833551
Mean Prediction Error: Percent Change minus RF   -0.233317
dtype: float64
P-values for this fold:
const     1.634735e-02
Mkt-RF    4.297249e-26
SMB       3.556057e-01
HML       2.455193e-12
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.575
Model:                                 OLS   Adj. R-squared:                  0.569
Method:                      Least Squares   F-statistic:                     94.72
Date:                     Thu, 09 Apr 2026   Prob (F-statistic):           8.37e-39
Time:                             14:03:17   Log-Likelihood:                -441.68
No. Observations:                      214   AIC:                             891.4
Df Residuals:                          210   BIC:                             904.8
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.3218      0.133      2.421      0.016       0.060       0.584
Mkt-RF         1.9650      0.162     12.156      0.000       1.646       2.284
SMB           -0.1820      0.197     -0.926      0.356      -0.570       0.206
HML           -0.9109      0.122     -7.446      0.000      -1.152      -0.670
==============================================================================
Omnibus:                       52.613   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              175.025
Skew:                           0.975   Prob(JB):                     9.86e-39
Kurtosis:                       6.979   Cond. No.                         1.95
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mkt-RF Beta: [ 1.84500941 -0.00972928 -0.83702304]
Alpha (Intercept): [0.20814222]
R2 score: 0.33807751444042866
Mean Prediction Error: Percent Change minus RF    0.154003
dtype: float64
P-values for this fold:
const     2.415328e-02
Mkt-RF    3.687245e-78
SMB       9.479384e-01
HML       1.083745e-17
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.690
Model:                                 OLS   Adj. R-squared:                  0.688
Method:                      Least Squares   F-statistic:                     342.2
Date:                     Thu, 09 Apr 2026   Prob (F-statistic):          5.93e-117
Time:                             14:03:17   Log-Likelihood:                -978.18
No. Observations:                      466   AIC:                             1964.
Df Residuals:                          462   BIC:                             1981.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2081      0.092      2.262      0.024       0.027       0.389
Mkt-RF         1.8450      0.081     22.909      0.000       1.687       2.003
SMB           -0.0097      0.149     -0.065      0.948      -0.302       0.283
HML           -0.8370      0.094     -8.921      0.000      -1.021      -0.653
==============================================================================
Omnibus:                       41.293   Durbin-Watson:                   1.951
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              155.805
Skew:                           0.279   Prob(JB):                     1.47e-34
Kurtosis:                       5.777   Cond. No.                         2.52
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mkt-RF Beta: [ 1.87950422 -0.2788887  -0.89761294]
Alpha (Intercept): [0.24119167]
R2 score: 0.49368421245613014
Mean Prediction Error: Percent Change minus RF   -0.094629
dtype: float64
P-values for this fold:
const     2.406875e-03
Mkt-RF    1.245386e-96
SMB       2.095485e-02
HML       5.150759e-25
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.597
Model:                                 OLS   Adj. R-squared:                  0.596
Method:                      Least Squares   F-statistic:                     353.0
Date:                     Thu, 09 Apr 2026   Prob (F-statistic):          1.59e-140
Time:                             14:03:17   Log-Likelihood:                -1555.8
No. Observations:                      718   AIC:                             3120.
Df Residuals:                          714   BIC:                             3138.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2412      0.079      3.046      0.002       0.086       0.397
Mkt-RF         1.8795      0.077     24.492      0.000       1.729       2.030
SMB           -0.2789      0.121     -2.314      0.021      -0.516      -0.042
HML           -0.8976      0.084    -10.732      0.000      -1.062      -0.733
==============================================================================
Omnibus:                      388.425   Durbin-Watson:                   2.014
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9912.008
Skew:                           1.893   Prob(JB):                         0.00
Kurtosis:                      20.804   Cond. No.                         2.05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Mkt-RF Beta: [ 1.98850958 -0.45688168 -1.02955487]
Alpha (Intercept): [0.2140143]
R2 score: 0.6555459162027635
Mean Prediction Error: Percent Change minus RF   -0.144129
dtype: float64
P-values for this fold:
const      2.883665e-03
Mkt-RF    3.083618e-118
SMB        2.571137e-05
HML        1.886152e-35
dtype: float64
                               OLS Regression Results
===================================================================================
Dep. Variable:     Percent Change minus RF   R-squared:                       0.571
Model:                                 OLS   Adj. R-squared:                  0.570
Method:                      Least Squares   F-statistic:                     428.7
Date:                     Thu, 09 Apr 2026   Prob (F-statistic):          5.06e-177
Time:                             14:03:17   Log-Likelihood:                -2150.4
No. Observations:                      970   AIC:                             4309.
Df Residuals:                          966   BIC:                             4328.
Df Model:                                3
Covariance Type:                 nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.2140      0.072      2.988      0.003       0.073       0.355
Mkt-RF         1.9885      0.074     26.725      0.000       1.842       2.135
SMB           -0.4569      0.108     -4.229      0.000      -0.669      -0.245
HML           -1.0296      0.080    -12.943      0.000      -1.186      -0.873
==============================================================================
Omnibus:                      345.463   Durbin-Watson:                   2.070
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5732.746
Skew:                           1.175   Prob(JB):                         0.00
Kurtosis:                      14.675   Cond. No.                         1.93
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.