In [28]:
# Import Dependencies
import yfinance
import pandas_datareader as pdr
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit
from sklearn.linear_model import LinearRegression

In [29]:
pdr.famafrench.get_available_datasets()

['F-F_Research_Data_Factors',
 'F-F_Research_Data_Factors_weekly',
 'F-F_Research_Data_Factors_daily',
 'F-F_Research_Data_5_Factors_2x3',
 'F-F_Research_Data_5_Factors_2x3_daily',
 'Portfolios_Formed_on_ME',
 'Portfolios_Formed_on_ME_Wout_Div',
 'Portfolios_Formed_on_ME_Daily',
 'Portfolios_Formed_on_BE-ME',
 'Portfolios_Formed_on_BE-ME_Wout_Div',
 'Portfolios_Formed_on_BE-ME_Daily',
 'Portfolios_Formed_on_OP',
 'Portfolios_Formed_on_OP_Wout_Div',
 'Portfolios_Formed_on_OP_Daily',
 'Portfolios_Formed_on_INV',
 'Portfolios_Formed_on_INV_Wout_Div',
 'Portfolios_Formed_on_INV_Daily',
 '6_Portfolios_2x3',
 '6_Portfolios_2x3_Wout_Div',
 '6_Portfolios_2x3_weekly',
 '6_Portfolios_2x3_daily',
 '25_Portfolios_5x5',
 '25_Portfolios_5x5_Wout_Div',
 '25_Portfolios_5x5_Daily',
 '100_Portfolios_10x10',
 '100_Portfolios_10x10_Wout_Div',
 '100_Portfolios_10x10_Daily',
 '6_Portfolios_ME_OP_2x3',
 '6_Portfolios_ME_OP_2x3_Wout_Div',
 '6_Portfolios_ME_OP_2x3_daily',
 '25_Portfolios_ME_OP_5x5',
 '25_Portfolios_ME_OP_5x5_Wout_Div',
 '25_Portfolios_ME_OP_5x5_daily',
 '100_Portfolios_ME_OP_10x10',
 '100_Portfolios_10x10_ME_OP_Wout_Div',
 '100_Portfolios_ME_OP_10x10_daily',
 '6_Portfolios_ME_INV_2x3',
 '6_Portfolios_ME_INV_2x3_Wout_Div',
 '6_Portfolios_ME_INV_2x3_daily',
 '25_Portfolios_ME_INV_5x5',
 '25_Portfolios_ME_INV_5x5_Wout_Div',
 '25_Portfolios_ME_INV_5x5_daily',
 '100_Portfolios_ME_INV_10x10',
 '100_Portfolios_10x10_ME_INV_Wout_Div',
 '100_Portfolios_ME_INV_10x10_daily',
 '25_Portfolios_BEME_OP_5x5',
 '25_Portfolios_BEME_OP_5x5_Wout_Div',
 '25_Portfolios_BEME_OP_5x5_daily',
 '25_Portfolios_BEME_INV_5x5',
 '25_Portfolios_BEME_INV_5x5_Wout_Div',
 '25_Portfolios_BEME_INV_5x5_daily',
 '25_Portfolios_OP_INV_5x5',
 '25_Portfolios_OP_INV_5x5_Wout_Div',
 '25_Portfolios_OP_INV_5x5_daily',
 '32_Portfolios_ME_BEME_OP_2x4x4',
 '32_Portfolios_ME_BEME_OP_2x4x4_Wout_Div',
 '32_Portfolios_ME_BEME_INV_2x4x4',
 '32_Portfolios_ME_BEME_INV_2x4x4_Wout_Div',
 '32_Portfolios_ME_OP_INV_2x4x4',
 '32_Portfolios_ME_OP_INV_2x4x4_Wout_Div',
 'Portfolios_Formed_on_E-P',
 'Portfolios_Formed_on_E-P_Wout_Div',
 'Portfolios_Formed_on_CF-P',
 'Portfolios_Formed_on_CF-P_Wout_Div',
 'Portfolios_Formed_on_D-P',
 'Portfolios_Formed_on_D-P_Wout_Div',
 '6_Portfolios_ME_EP_2x3',
 '6_Portfolios_ME_EP_2x3_Wout_Div',
 '6_Portfolios_ME_CFP_2x3',
 '6_Portfolios_ME_CFP_2x3_Wout_Div',
 '6_Portfolios_ME_DP_2x3',
 '6_Portfolios_ME_DP_2x3_Wout_Div',
 'F-F_Momentum_Factor',
 'F-F_Momentum_Factor_daily',
 '6_Portfolios_ME_Prior_12_2',
 '6_Portfolios_ME_Prior_12_2_Daily',
 '25_Portfolios_ME_Prior_12_2',
 '25_Portfolios_ME_Prior_12_2_Daily',
 '10_Portfolios_Prior_12_2',
 '10_Portfolios_Prior_12_2_Daily',
 'F-F_ST_Reversal_Factor',
 'F-F_ST_Reversal_Factor_daily',
 '6_Portfolios_ME_Prior_1_0',
 '6_Portfolios_ME_Prior_1_0_Daily',
 '25_Portfolios_ME_Prior_1_0',
 '25_Portfolios_ME_Prior_1_0_Daily',
 '10_Portfolios_Prior_1_0',
 '10_Portfolios_Prior_1_0_Daily',
 'F-F_LT_Reversal_Factor',
 'F-F_LT_Reversal_Factor_daily',
 '6_Portfolios_ME_Prior_60_13',
 '6_Portfolios_ME_Prior_60_13_Daily',
 '25_Portfolios_ME_Prior_60_13',
 '25_Portfolios_ME_Prior_60_13_Daily',
 '10_Portfolios_Prior_60_13',
 '10_Portfolios_Prior_60_13_Daily',
 'Portfolios_Formed_on_AC',
 '25_Portfolios_ME_AC_5x5',
 'Portfolios_Formed_on_BETA',
 '25_Portfolios_ME_BETA_5x5',
 'Portfolios_Formed_on_NI',
 '25_Portfolios_ME_NI_5x5',
 'Portfolios_Formed_on_VAR',
 '25_Portfolios_ME_VAR_5x5',
 'Portfolios_Formed_on_RESVAR',
 '25_Portfolios_ME_RESVAR_5x5',
 '5_Industry_Portfolios',
 '5_Industry_Portfolios_Wout_Div',
 '5_Industry_Portfolios_daily',
 '10_Industry_Portfolios',
 '10_Industry_Portfolios_Wout_Div',
 '10_Industry_Portfolios_daily',
 '12_Industry_Portfolios',
 '12_Industry_Portfolios_Wout_Div',
 '12_Industry_Portfolios_daily',
 '17_Industry_Portfolios',
 '17_Industry_Portfolios_Wout_Div',
 '17_Industry_Portfolios_daily',
 '30_Industry_Portfolios',
 '30_Industry_Portfolios_Wout_Div',
 '30_Industry_Portfolios_daily',
 '38_Industry_Portfolios',
 '38_Industry_Portfolios_Wout_Div',
 '38_Industry_Portfolios_daily',
 '48_Industry_Portfolios',
 '48_Industry_Portfolios_Wout_Div',
 '48_Industry_Portfolios_daily',
 '49_Industry_Portfolios',
 '49_Industry_Portfolios_Wout_Div',
 '49_Industry_Portfolios_daily',
 'ME_Breakpoints',
 'BE-ME_Breakpoints',
 'OP_Breakpoints',
 'INV_Breakpoints',
 'E-P_Breakpoints',
 'CF-P_Breakpoints',
 'D-P_Breakpoints',
 'Prior_2-12_Breakpoints',
 'Developed_3_Factors',
 'Developed_3_Factors_Daily',
 'Developed_ex_US_3_Factors',
 'Developed_ex_US_3_Factors_Daily',
 'Europe_3_Factors',
 'Europe_3_Factors_Daily',
 'Japan_3_Factors',
 'Japan_3_Factors_Daily',
 'Asia_Pacific_ex_Japan_3_Factors',
 'Asia_Pacific_ex_Japan_3_Factors_Daily',
 'North_America_3_Factors',
 'North_America_3_Factors_Daily',
 'Developed_5_Factors',
 'Developed_5_Factors_Daily',
 'Developed_ex_US_5_Factors',
 'Developed_ex_US_5_Factors_Daily',
 'Europe_5_Factors',
 'Europe_5_Factors_Daily',
 'Japan_5_Factors',
 'Japan_5_Factors_Daily',
 'Asia_Pacific_ex_Japan_5_Factors',
 'Asia_Pacific_ex_Japan_5_Factors_Daily',
 'North_America_5_Factors',
 'North_America_5_Factors_Daily',
 'Developed_Mom_Factor',
 'Developed_Mom_Factor_Daily',
 'Developed_ex_US_Mom_Factor',
 'Developed_ex_US_Mom_Factor_Daily',
 'Europe_Mom_Factor',
 'Europe_Mom_Factor_Daily',
 'Japan_Mom_Factor',
 'Japan_Mom_Factor_Daily',
 'Asia_Pacific_ex_Japan_MOM_Factor',
 'Asia_Pacific_ex_Japan_MOM_Factor_Daily',
 'North_America_Mom_Factor',
 'North_America_Mom_Factor_Daily',
 'Developed_6_Portfolios_ME_BE-ME',
 'Developed_6_Portfolios_ME_BE-ME_daily',
 'Developed_ex_US_6_Portfolios_ME_BE-ME',
 'Developed_ex_US_6_Portfolios_ME_BE-ME_daily',
 'Europe_6_Portfolios_ME_BE-ME',
 'Europe_6_Portfolios_ME_BE-ME_daily',
 'Japan_6_Portfolios_ME_BE-ME',
 'Japan_6_Portfolios_ME_BE-ME_daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_BE-ME_daily',
 'North_America_6_Portfolios_ME_BE-ME',
 'North_America_6_Portfolios_ME_BE-ME_daily',
 'Developed_25_Portfolios_ME_BE-ME',
 'Developed_25_Portfolios_ME_BE-ME_daily',
 'Developed_ex_US_25_Portfolios_ME_BE-ME',
 'Developed_ex_US_25_Portfolios_ME_BE-ME_daily',
 'Europe_25_Portfolios_ME_BE-ME',
 'Europe_25_Portfolios_ME_BE-ME_daily',
 'Japan_25_Portfolios_ME_BE-ME',
 'Japan_25_Portfolios_ME_BE-ME_daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_BE-ME_daily',
 'North_America_25_Portfolios_ME_BE-ME',
 'North_America_25_Portfolios_ME_BE-ME_daily',
 'Developed_6_Portfolios_ME_OP',
 'Developed_6_Portfolios_ME_OP_Daily',
 'Developed_ex_US_6_Portfolios_ME_OP',
 'Developed_ex_US_6_Portfolios_ME_OP_Daily',
 'Europe_6_Portfolios_ME_OP',
 'Europe_6_Portfolios_ME_OP_Daily',
 'Japan_6_Portfolios_ME_OP',
 'Japan_6_Portfolios_ME_OP_Daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_OP',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_OP_Daily',
 'North_America_6_Portfolios_ME_OP',
 'North_America_6_Portfolios_ME_OP_Daily',
 'Developed_25_Portfolios_ME_OP',
 'Developed_25_Portfolios_ME_OP_Daily',
 'Developed_ex_US_25_Portfolios_ME_OP',
 'Developed_ex_US_25_Portfolios_ME_OP_Daily',
 'Europe_25_Portfolios_ME_OP',
 'Europe_25_Portfolios_ME_OP_Daily',
 'Japan_25_Portfolios_ME_OP',
 'Japan_25_Portfolios_ME_OP_Daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_OP',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_OP_Daily',
 'North_America_25_Portfolios_ME_OP',
 'North_America_25_Portfolios_ME_OP_Daily',
 'Developed_6_Portfolios_ME_INV',
 'Developed_6_Portfolios_ME_INV_Daily',
 'Developed_ex_US_6_Portfolios_ME_INV',
 'Developed_ex_US_6_Portfolios_ME_INV_Daily',
 'Europe_6_Portfolios_ME_INV',
 'Europe_6_Portfolios_ME_INV_Daily',
 'Japan_6_Portfolios_ME_INV',
 'Japan_6_Portfolios_ME_INV_Daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_INV',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_INV_Daily',
 'North_America_6_Portfolios_ME_INV',
 'North_America_6_Portfolios_ME_INV_Daily',
 'Developed_25_Portfolios_ME_INV',
 'Developed_25_Portfolios_ME_INV_Daily',
 'Developed_ex_US_25_Portfolios_ME_INV',
 'Developed_ex_US_25_Portfolios_ME_INV_Daily',
 'Europe_25_Portfolios_ME_INV',
 'Europe_25_Portfolios_ME_INV_Daily',
 'Japan_25_Portfolios_ME_INV',
 'Japan_25_Portfolios_ME_INV_Daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_INV',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_INV_Daily',
 'North_America_25_Portfolios_ME_INV',
 'North_America_25_Portfolios_ME_INV_Daily',
 'Developed_6_Portfolios_ME_Prior_12_2',
 'Developed_6_Portfolios_ME_Prior_250_20_daily',
 'Developed_ex_US_6_Portfolios_ME_Prior_12_2',
 'Developed_ex_US_6_Portfolios_ME_Prior_250_20_daily',
 'Europe_6_Portfolios_ME_Prior_12_2',
 'Europe_6_Portfolios_ME_Prior_250_20_daily',
 'Japan_6_Portfolios_ME_Prior_12_2',
 'Japan_6_Portfolios_ME_Prior_250_20_daily',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_12_2',
 'Asia_Pacific_ex_Japan_6_Portfolios_ME_Prior_250_20_daily',
 'North_America_6_Portfolios_ME_Prior_12_2',
 'North_America_6_Portfolios_ME_Prior_250_20_daily',
 'Developed_25_Portfolios_ME_Prior_12_2',
 'Developed_25_Portfolios_ME_Prior_250_20_daily',
 'Developed_ex_US_25_Portfolios_ME_Prior_12_2',
 'Developed_ex_US_25_Portfolios_ME_Prior_250_20_daily',
 'Europe_25_Portfolios_ME_Prior_12_2',
 'Europe_25_Portfolios_ME_Prior_250_20_daily',
 'Japan_25_Portfolios_ME_Prior_12_2',
 'Japan_25_Portfolios_ME_Prior_250_20_daily',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_12_2',
 'Asia_Pacific_ex_Japan_25_Portfolios_ME_Prior_250_20_daily',
 'North_America_25_Portfolios_ME_Prior_12_2',
 'North_America_25_Portfolios_ME_Prior_250_20_daily',
 'Developed_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Europe_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Japan_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'North_America_32_Portfolios_ME_BE-ME_OP_2x4x4',
 'Developed_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Europe_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'North_America_32_Portfolios_ME_BE-ME_INV(TA)_2x4x4',
 'Developed_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Developed_ex_US_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Europe_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Asia_Pacific_ex_Japan_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'North_America_32_Portfolios_ME_INV(TA)_OP_2x4x4',
 'Emerging_5_Factors',
 'Emerging_MOM_Factor',
 'Emerging_Markets_6_Portfolios_ME_BE-ME',
 'Emerging_Markets_6_Portfolios_ME_OP',
 'Emerging_Markets_6_Portfolios_ME_INV',
 'Emerging_Markets_6_Portfolios_ME_Prior_12_2',
 'Emerging_Markets_4_Portfolios_BE-ME_OP',
 'Emerging_Markets_4_Portfolios_OP_INV',
 'Emerging_Markets_4_Portfolios_BE-ME_INV']

In [30]:
# Daily 3 Factor
df = pdr.famafrench.FamaFrenchReader('F-F_Research_Data_Factors_daily')

In [31]:
data = df.read()

/var/folders/mr/nzdp38cj3cz3b0gcgyvws4c40000gp/T/ipykernel_39109/1535062722.py:1: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  data = df.read()

In [32]:
data

{0:             Mkt-RF   SMB   HML    RF
 Date
 2021-04-01    1.27  0.30 -0.02  0.00
 2021-04-05    1.28 -0.59 -0.71  0.00
 2021-04-06    0.00 -0.31  0.09  0.00
 2021-04-07   -0.11 -1.59  0.30  0.00
 2021-04-08    0.62  0.59 -1.17  0.00
 ...            ...   ...   ...   ...
 2026-02-23   -1.18 -0.30 -1.31  0.01
 2026-02-24    0.83  0.51 -0.66  0.01
 2026-02-25    0.79 -0.37  0.49  0.01
 2026-02-26   -0.47  0.63  0.32  0.01
 2026-02-27   -0.51 -0.44 -1.25  0.01

 [1233 rows x 4 columns],
 'DESCR': 'F-F Research Data Factors daily\n-------------------------------\n\nThis file was created by using the 202602 CRSP database. The Tbill return is the simple daily rate that, over the number of trading days compounds to 1-month TBill rate. The 1-month TBill rate data until 202405 are from Ibbotson Associates. Starting from 202406, the 1-month TBill rate is from ICE BofA US 1-Month Treasury Bill Index. Copyright 2026 Eugene F. Fama and Kenneth R. French\n\n  0 : (1233 rows x 4 cols)'}

In [33]:
data[0]

            Mkt-RF   SMB   HML    RF
Date
2021-04-01    1.27  0.30 -0.02  0.00
2021-04-05    1.28 -0.59 -0.71  0.00
2021-04-06    0.00 -0.31  0.09  0.00
2021-04-07   -0.11 -1.59  0.30  0.00
2021-04-08    0.62  0.59 -1.17  0.00
...            ...   ...   ...   ...
2026-02-23   -1.18 -0.30 -1.31  0.01
2026-02-24    0.83  0.51 -0.66  0.01
2026-02-25    0.79 -0.37  0.49  0.01
2026-02-26   -0.47  0.63  0.32  0.01
2026-02-27   -0.51 -0.44 -1.25  0.01

[1233 rows x 4 columns]

In [34]:
AAPL = yfinance.Ticker("NVDA")

In [35]:
AAPL.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation operates as a data center scale AI infrastructure company. The company operates through two segments, Compute & Networking, and Graphics segments. The Compute & Networking segment provides data center accelerated computing and networking platforms and artificial intelligence solutions and software, and automotive platforms and autonomous and electric vehicle solutions, including software. The Graphics segment offers GeForce GPUs for gaming and PCs; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics. The company's products are used in gaming, professional visualization, data center, and automotive markets. The company sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants worldwide. It has a collaboration with Tech Mahindra Limited to develop artificial intelligence powered telco network operations reasoning agent. The company has a strategic partnership with Lumentum Holdings Inc. to develop optics technologies for AI and data centers. It also has a strategic partnership with Nebius Group N.V. to develop and deploy hyperscale cloud for the artificial intelligence market. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 42000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 62,
   'title': 'Co-Founder, CEO & Director',
   'yearBorn': 1963,
   'fiscalYear': 2025,
   'totalPay': 11054945,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 58,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1512641,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 70,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 1379071,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter J.D.',
   'age': 58,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1362989,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 70,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 2313851,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2025,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 56,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 64,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Toshiya  Hari',
   'title': 'Vice President of Investor Relations & Strategic Finance',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mylene  Mangalindan',
   'title': 'Vice President of Corporate Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 9,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 165.17,
 'open': 166.97,
 'dayLow': 166.96,
 'dayHigh': 174.62,
 'regularMarketPreviousClose': 165.17,
 'regularMarketOpen': 166.97,
 'regularMarketDayLow': 166.96,
 'regularMarketDayHigh': 174.62,
 'dividendRate': 0.04,
 'dividendYield': 0.02,
 'exDividendDate': 1773187200,
 'payoutRatio': 0.0082,
 'fiveYearAvgDividendYield': 0.05,
 'beta': 2.375,
 'trailingPE': 35.51935,
 'forwardPE': 15.688602,
 'volume': 214649276,
 'regularMarketVolume': 214649276,
 'averageVolume': 180628640,
 'averageVolume10days': 181164630,
 'averageDailyVolume10Day': 181164630,
 'bid': 174.03,
 'ask': 174.35,
 'bidSize': 20,
 'askSize': 1,
 'marketCap': 4238791933952,
 'nonDilutedMarketCap': 4598904830000,
 'fiftyTwoWeekLow': 86.62,
 'fiftyTwoWeekHigh': 212.19,
 'allTimeHigh': 212.19,
 'allTimeLow': 0.033333,
 'priceToSalesTrailing12Months': 19.629671,
 'fiftyDayAverage': 183.0526,
 'twoHundredDayAverage': 179.3383,
 'trailingAnnualDividendRate': 0.04,
 'trailingAnnualDividendYield': 0.00024217472,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3962486915072,
 'profitMargins': 0.55603004,
 'floatShares': 23322168000,
 'sharesOutstanding': 24300000000,
 'sharesShort': 229241850,
 'sharesShortPriorMonth': 254311707,
 'sharesShortPreviousMonthDate': 1770940800,
 'dateShortInterest': 1773360000,
 'sharesPercentSharesOut': 0.0094,
 'heldPercentInsiders': 0.04212,
 'heldPercentInstitutions': 0.69757,
 'shortRatio': 1.28,
 'shortPercentOfFloat': 0.0098,
 'impliedSharesOutstanding': 24305000000,
 'bookValue': 6.472,
 'priceToBook': 26.946846,
 'lastFiscalYearEnd': 1769299200,
 'nextFiscalYearEnd': 1800835200,
 'mostRecentQuarter': 1769299200,
 'earningsQuarterlyGrowth': 0.945,
 'netIncomeToCommon': 120066998272,
 'trailingEps': 4.91,
 'forwardEps': 11.11635,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 18.35,
 'enterpriseToEbitda': 29.742,
 '52WeekChange': 0.49950063,
 'SandP52WeekChange': 0.1261568,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1773187200,
 'quoteType': 'EQUITY',
 'currentPrice': 174.4,
 'targetHighPrice': 380.0,
 'targetLowPrice': 140.0,
 'targetMeanPrice': 268.22195,
 'targetMedianPrice': 265.0,
 'recommendationMean': 1.28333,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 56,
 'totalCash': 62556000256,
 'totalCashPerShare': 2.574,
 'ebitda': 133230002176,
 'totalDebt': 11411999744,
 'quickRatio': 3.141,
 'currentRatio': 3.905,
 'totalRevenue': 215938007040,
 'debtToEquity': 7.255,
 'revenuePerShare': 8.865,
 'returnOnAssets': 0.51188,
 'returnOnEquity': 1.01485,
 'grossProfits': 153462996992,
 'freeCashflow': 58128998400,
 'operatingCashflow': 102717997056,
 'earningsGrowth': 0.956,
 'revenueGrowth': 0.732,
 'grossMargins': 0.71068,
 'ebitdaMargins': 0.61698,
 'operatingMargins': 0.65024,
 'financialCurrency': 'USD',
 'symbol': 'NVDA',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'POST',
 'regularMarketChangePercent': 5.5881796,
 'regularMarketPrice': 174.4,
 'corporateActions': [],
 'postMarketTime': 1774989768,
 'regularMarketTime': 1774987205,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_32307',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 917015400000,
 'postMarketChangePercent': 0.063309975,
 'postMarketPrice': 174.5104,
 'postMarketChange': 0.1104126,
 'regularMarketChange': 9.229996,
 'regularMarketDayRange': '166.96 - 174.62',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 180628640,
 'fiftyTwoWeekLowChange': 87.77999,
 'fiftyTwoWeekLowChangePercent': 1.0133917,
 'fiftyTwoWeekRange': '86.62 - 212.19',
 'fiftyTwoWeekHighChange': -37.79001,
 'fiftyTwoWeekHighChangePercent': -0.17809515,
 'fiftyTwoWeekChangePercent': 49.95006,
 'dividendDate': 1775001600,
 'earningsTimestamp': 1779307200,
 'earningsTimestampStart': 1779307200,
 'earningsTimestampEnd': 1779307200,
 'earningsCallTimestampStart': 1772056800,
 'earningsCallTimestampEnd': 1772056800,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 4.91,
 'epsForward': 11.11635,
 'epsCurrentYear': 8.29457,
 'priceEpsCurrentYear': 21.025803,
 'fiftyDayAverageChange': -8.652603,
 'fiftyDayAverageChangePercent': -0.047268398,
 'twoHundredDayAverageChange': -4.9383087,
 'twoHundredDayAverageChangePercent': -0.027536275,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'prevName': 'Usual Stablecoin',
 'nameChangeDate': '2026-03-31',
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'displayName': 'NVIDIA',
 'trailingPegRatio': 1.0002}

In [36]:
history = AAPL.history(period='5y')

In [37]:
history = history.reset_index()

In [38]:
history['Date'] = history['Date'].dt.date

In [39]:
history

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-04-01,13.538127,13.835128,13.477280,13.777025,308276000,0.0,0.0
1,2021-04-05,13.832634,13.978766,13.698472,13.952332,255672000,0.0,0.0
2,2021-04-06,13.964552,14.018915,13.738872,13.826650,191744000,0.0,0.0
3,2021-04-07,13.845852,14.207690,13.677028,14.107942,251284000,0.0,0.0
4,2021-04-08,14.216917,14.435117,14.213176,14.281006,244416000,0.0,0.0
...,...,...,...,...,...,...,...,...
1250,2026-03-25,177.100006,181.220001,176.850006,178.679993,162602100,0.0,0.0
1251,2026-03-26,176.070007,176.509995,171.139999,171.240005,186152200,0.0,0.0
1252,2026-03-27,170.000000,170.970001,167.009995,167.520004,196212700,0.0,0.0
1253,2026-03-30,168.779999,169.449997,164.270004,165.169998,185627000,0.0,0.0
1254,2026-03-31,166.970001,174.619995,166.960007,174.399994,214649476,0.0,0.0

In [40]:
history['Previous Close'] = history['Close'].shift(1)

In [41]:
history['Percentage Change'] = ((history['Close'] - history['Previous Close']) / history['Previous Close']) * 100

In [42]:
history = history.dropna()

In [43]:
condensed_history = history[['Date', 'Percentage Change']]

In [44]:
condensed_history

            Date  Percentage Change
1     2021-04-05           1.272461
2     2021-04-06          -0.900802
3     2021-04-07           2.034419
4     2021-04-08           1.226715
5     2021-04-09           0.579724
...          ...                ...
1250  2026-03-25           1.986299
1251  2026-03-26          -4.163861
1252  2026-03-27          -2.172390
1253  2026-03-30          -1.402821
1254  2026-03-31           5.588179

[1254 rows x 2 columns]

In [45]:
Fama_3_Factor = data[0].reset_index()

In [46]:
Fama_3_Factor['Date'] = Fama_3_Factor['Date'].dt.date

In [47]:
Fama_3_Factor

            Date  Mkt-RF   SMB   HML    RF
0     2021-04-01    1.27  0.30 -0.02  0.00
1     2021-04-05    1.28 -0.59 -0.71  0.00
2     2021-04-06    0.00 -0.31  0.09  0.00
3     2021-04-07   -0.11 -1.59  0.30  0.00
4     2021-04-08    0.62  0.59 -1.17  0.00
...          ...     ...   ...   ...   ...
1228  2026-02-23   -1.18 -0.30 -1.31  0.01
1229  2026-02-24    0.83  0.51 -0.66  0.01
1230  2026-02-25    0.79 -0.37  0.49  0.01
1231  2026-02-26   -0.47  0.63  0.32  0.01
1232  2026-02-27   -0.51 -0.44 -1.25  0.01

[1233 rows x 5 columns]

In [48]:
Combined = Fama_3_Factor.merge(condensed_history, on='Date', how='inner')

In [49]:
Combined

            Date  Mkt-RF   SMB   HML    RF  Percentage Change
0     2021-04-05    1.28 -0.59 -0.71  0.00           1.272461
1     2021-04-06    0.00 -0.31  0.09  0.00          -0.900802
2     2021-04-07   -0.11 -1.59  0.30  0.00           2.034419
3     2021-04-08    0.62  0.59 -1.17  0.00           1.226715
4     2021-04-09    0.65 -0.64  0.15  0.00           0.579724
...          ...     ...   ...   ...   ...                ...
1227  2026-02-23   -1.18 -0.30 -1.31  0.01           0.911389
1228  2026-02-24    0.83  0.51 -0.66  0.01           0.678672
1229  2026-02-25    0.79 -0.37  0.49  0.01           1.405230
1230  2026-02-26   -0.47  0.63  0.32  0.01          -5.456124
1231  2026-02-27   -0.51 -0.44 -1.25  0.01          -4.164631

[1232 rows x 6 columns]

In [50]:
Combined['Percent Change minus RF'] = (Combined['Percentage Change'] - (Combined['RF']))

In [51]:
Combined = Combined.drop(columns = 'Percentage Change')

In [52]:
Combined.columns

Index(['Date', 'Mkt-RF', 'SMB', 'HML', 'RF', 'Percent Change minus RF'], dtype='object')

In [53]:
tscv = TimeSeriesSplit(n_splits=4, test_size=252, gap=5)

X = Combined[['Mkt-RF', 'SMB', 'HML']]
y = Combined[['Percent Change minus RF']]

for train_index, test_index in tscv.split(Combined):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and Fit
    model = LinearRegression()
    model.fit(X_train, y_train)
    
    # Check your Factor Loadings (Betas) for this fold
    print(f"Mkt-RF Beta: {model.coef_[0]}")
    print(f"Alpha (Intercept): {model.intercept_}")

Mkt-RF Beta: [ 1.94352242 -0.18571219 -0.90157969]
Alpha (Intercept): [0.30361803]
Mkt-RF Beta: [ 1.84257172 -0.01736447 -0.83464051]
Alpha (Intercept): [0.20257736]
Mkt-RF Beta: [ 1.87633704 -0.28013241 -0.89477998]
Alpha (Intercept): [0.23635299]
Mkt-RF Beta: [ 1.98512919 -0.45640296 -1.0269714 ]
Alpha (Intercept): [0.2097566]